### ISSUE TITLE
Re-enter pin on invalid code

### ISSUE THREAD

**Issue by colinbes** [Tkko/Flutter_Pinput#102]
What is best way to allow user to reenter pin if code was invalid?

On onCompleted I call function to validate pin entered and in invalid I am clearing TextEditController and requesting focus.

In `Pinput` I have:
```
onCompleted: (pin) => checkAuth(pin),
```
where checkAuth is
```
  void checkAuth(String value) {
    setState(() {
      pinController.clear();
      // pinController.selection = TextSelection.fromPosition(const TextPosition(offset: 0));
      pinputFocusNode.requestFocus();
    });
  }
```
In testing I have removed tests to validate pin as I am just testing the invalid case. On calling checkAuth, the pin fields all clear but none have focus.

PinPut is configured as:
```
Pinput(
          length: 4,
          autofocus: true,
          controller: pinController,
          inputFormatters: [FilteringTextInputFormatter.digitsOnly],
          focusNode: pinputFocusNode,
          separator: Container(
            height: 64,
            width: 1,
            color: Colors.white,
          ),
          defaultPinTheme: defaultPinTheme,
          focusedPinTheme: defaultPinTheme.copyWith(
            decoration: BoxDecoration(color: Colors.blue[100]),
          ),
          // validator: (s) {
          //   return s == '2222' ? null : 'Pin is incorrect';
          // },
          onChanged: (value) => print(value),
          keyboardType: TextInputType.number,
          showCursor: true,
          onCompleted: (pin) => checkAuth(pin),
        );
```

If I add a floating action calling same code as checkAuth then the fields clear and first pin field gets focus.

**Comment by Tkko** [comment]
Hi @colinbes,

**Solution 1:**
Set `closeKeyboardWhenCompleted: false` 
```
  void checkAuth(String value) {
    setState(() {
      pinController.clear();
    });
  }
```


**Solution 2:**
```
  void checkAuth(String value) {
    setState(() {
      pinController.clear();
      Future.delayed(Duration.zero).then((_) => focusNode.requestFocus());
    });
  }
```

**Comment by colinbes** [comment]
Ah, I should have thought of 2nd option. I didn't notice keyboard setting but I confirm both suggestion work!

Thanks

**Comment by colinbes** [comment]
Ah, I should have thought of 2nd option. I didn't notice keyboard setting but I confirm both suggestion work!

Thanks
