### ISSUE TITLE
Provide a way to disable the cursor animation

### ISSUE THREAD

**Issue by vHanda** [Tkko/Flutter_Pinput#103]
Hello.

I've been using these tests with some integration tests, and it results in them being stuck as they often have steps which wait for no more paints to occur. With this widget, the cursor keeps blinking no matter what, and therefore the paints never stop.

**Comment by Tkko** [comment]
Hey, did you try showCursor flag?

**Comment by vHanda** [comment]
I did. However, what would be ideal is to have some way to show the cursor, but not animate it.

This also seems to interfere with golden tests, as they also rely on all the painting finishing.

**Comment by Tkko** [comment]
Hey, sorry for the late response.

## [2.2.13](https://github.com/Tkko/Flutter_Pinput/releases/tag/v2.2.13) -03/10/2022
- Bumped minimum Flutter SDK version to 2.0.0
- Added
  | Property   | Meaning/Default |
  |------------|:-------:|
  | isCursorAnimationEnabled  | true |

**Comment by vHanda** [comment]
@Tkko : Please, nothing to apologize for.

I'm super happy that you've even solved this. You're providing an awesome open source project, and I'm just happy for this extra package.

Thank you for solving this issue.

If you're ever in Barcelona, Spain, please shout out, I owe you a beer.
