### ISSUE TITLE
FocusTrapArea

### ISSUE THREAD

**Issue by parameshmamidisetti** [Tkko/Flutter_Pinput#106]
Error: The method 'FocusTrapArea' isn't defined for the class '_PinputState'.
 - '_PinputState' is from 'package:pinput/src/pinput.dart' ('/C:/Users/paramesh/AppData/Local/Pub/Cache/hosted/pub.dev/pinput-2.2.16/lib/src/pinput.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FocusTrapArea'.
      child: FocusTrapArea(

**Comment by khaidem** [comment]
I have also error  this when I  change flutter channel to stable it will solve

**Comment by kamami** [comment]
Same issue

**Comment by Tkko** [comment]
Hey guys, please take a look at https://github.com/Tkko/Flutter_Pinput/issues/98#issuecomment-1212291722

**Comment by Tkko** [comment]
Duplicate of https://github.com/Tkko/Flutter_Pinput/issues/98
