### ISSUE TITLE
Allow for `TextCapitalization`

### ISSUE THREAD

**Issue by mwgriffiths88** [Tkko/Flutter_PinPut#11]
Flutter has a [`textCapitalization` property](https://docs.flutter.io/flutter/material/TextField/textCapitalization.html) for `TextField`, which allows auto-capitalisation to be specified on characters, sentences, and words.

It would be useful is this was also added to `PinPut`, particularly for cases where the `keyboardType` is set to `TextInputType.text`.

**Comment by mwgriffiths88** [comment]
https://github.com/Tkko/Flutter_PinPut/pull/12

**Comment by Tkko** [comment]
Merged your request, thanks.
