### ISSUE TITLE
A suggestion, you might like to make [suggestion]

### ISSUE THREAD

**Issue by MohsenHaydari** [Tkko/Flutter_Pinput#112]
```InlineSpan``` is used in the Flutter text field, which means that the entire text changes with the direction of the context or selection.
The problem I have with my program, because it supports all languages when typing, I can't just change the desired line to the detected direction.
In my opinion, you can create a package that detects and displays the direction in each new line in the text field, like what you did in this package and you are familiar with the text field state objects.
Please see these 2 links to understand what I mean
[Link1](https://stackoverflow.com/questions/72238125/flutter-textfield-with-auto-textdirection)
[Link2](https://stackoverflow.com/questions/74917544/flutter-textfield-direction-line-by-line)

I spent some time on it by editing the text field file and it can probably be fixed perfectly
```
 
  Widget buildText() {
    List<String> list = text.replaceAll("\n", "&&\n").split("&&");

    return Container(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
      decoration: BoxDecoration(
          color: Colors.grey[100], borderRadius: BorderRadius.circular(8)),
      child: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: List.generate(list.length, (index) {
            if (list[index].isNotEmpty && isRTL(list[index])) {
              return Directionality(
                textDirection: TextDirection.rtl,
                child: Row(
                  children: [
                    Text(
                      list[index],
                      style: widget.style,
                    )
                  ],
                ),
              );
            }
            return Text(
              list[index],
              style: widget.style,
            );
          }),
        ),
      ),
    );
  }
```
thanks, for your great package and good luck

**Comment by Tkko** [comment]
Hey @MohsenHaydari, thanks for the suggestion.
I can see the need of that widget but I'm not available at the moment, so I would recommend [super_editor](https://pub.dev/packages/super_editor), it's not what you described but I think they can/will do it.
