### ISSUE TITLE
Numbers not typing

### ISSUE THREAD

**Issue by descobee** [Tkko/Flutter_Pinput#113]
Hi. Please in trying to implement the package, I encountered an error whereby the first character of the pin field is not accepting numbers, only special characters. And this happens only on Android, on iOS it's working fine.

https://user-images.githubusercontent.com/61969550/211009383-15f69df0-400e-423e-b5e4-490c486ef552.mp4

**Comment by Tkko** [comment]
Hey @descobee, do you use any `inputFormatters` ?

**Comment by descobee** [comment]
No @Tkko I'm not.

**Comment by Tkko** [comment]
@descobee could you share small reproducable snippet

**Comment by vaidic-dodwani** [comment]
https://user-images.githubusercontent.com/59657947/213692952-a2034e2b-43f5-41c3-84ea-5a6eeef66fba.mp4

experiencing the same issue here,

```
 final pinController = TextEditingController();

Pinput(
                onCompleted: (value) {
                  if (buttonFunction != null) {
                    buttonFunction!(int.parse(value));
                  }
                },
                length: 4,
                controller: pinController,
                defaultPinTheme: defaultPinTheme,
                focusedPinTheme: focusedPinTheme,
                followingPinTheme: followingPinTheme,
              ),
              
              final defaultPinTheme = PinTheme(
  height: 56,
  width: 56,
  textStyle: titleMedium(),
  decoration: const BoxDecoration(
    border: Border(bottom: BorderSide(width: 1.0, color: Colors.transparent)),
  ),
);

final focusedPinTheme = PinTheme(
  height: 56,
  width: 56,
  textStyle: titleMedium(),
  decoration: const BoxDecoration(
    border: Border(bottom: BorderSide(width: 1.0, color: Palette.primaryColor)),
  ),
);

final followingPinTheme = PinTheme(
  height: 56,
  width: 56,
  textStyle: titleMedium(),
  decoration: const BoxDecoration(
    border: Border(
        bottom: BorderSide(width: 1.0, color: Palette.secondaryOffWhiteColor)),
  ),
);

```


is everything I have used for the widget

for the entire code please checkout my repo:


[Otp_Box](https://github.com/vaidic-dodwani/CryptbeeApp/blob/main/lib/Screens/Utilities/Widgets/otp_box.dart).

**Comment by Tkko** [comment]
@vaidic-dodwani, does it work properly on Android emulator? Which device are you using?
Could you share the output of `flutter --version` command?

**Comment by vaidic-dodwani** [comment]
> @vaidic-dodwani, does it work properly on Android emulator? Which device are you using? Could you share the output of `flutter --version` command?

`flutter --version` output
```
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (5 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```


Device Using: OnePlus 7T
Android Version:11

Same behavior on Android Emulator

**Comment by Tkko** [comment]
@vaidic-dodwani Check if the same behavior exists in Standard `TextFormField`

```
    TextFormField(
      controller: pinController,
      keyboardType: TextInputType.number,
      inputFormatters: [
        LengthLimitingTextInputFormatter(
          4,
          maxLengthEnforcement: MaxLengthEnforcement.enforced,
        ),
      ],
    );
```

**Comment by vaidic-dodwani** [comment]
> 

Yup same behavior on TextFormField

should I send the corresponding video?

**Comment by Tkko** [comment]
@vaidic-dodwani Now try and remove inputFormatters. 
I'm not sure what but something is wrong with EditableText which is an underlying widget of both TextFormField and Pinput

**Comment by vaidic-dodwani** [comment]
> @vaidic-dodwani Now try and remove inputFormatters. I'm not sure what but something is wrong with EditableText which is an underlying widget of both TextFormField and Pinput

Still the same behavior

**Comment by Tkko** [comment]
@vaidic-dodwani Yeah, it's seems like an Flutter issue, I advice you to create a separate issue on Flutter repo, and share the url here.
Thanks
