### ISSUE TITLE
Android - Autofill sms code-  digits not displayed

### ISSUE THREAD

**Issue by sarp86** [Tkko/Flutter_Pinput#115]
Hello guys,

When I receive the sms from Firebase on Android, the text fields are not filled in with the numbers, but I can click the next button and the phone number is verified. (If code is not entered next button is disabled)

![IMG_0661 2](https://user-images.githubusercontent.com/44084914/212438456-0e4c4300-bbb4-428b-8fa9-ef7c65fb6019.jpg)

Before I click on the next button to verify, If I click on the text fields, I can type in a code (fields empty) and the next button change from active to not active.

(iOS works well and digits shown in textfield)

**Comment by Tkko** [comment]
Hi @sarp86 Firebase Auth handles reading the sms code automatically, so you have to set Pinput's `androidSmsAutofillMethod` to none:
``` dart
    Pinput(
      androidSmsAutofillMethod: AndroidSmsAutofillMethod.none,
      controller: pinController,
    );
```
And set pinController's value in `verificationCompleted` callback:
``` dart
    await FirebaseAuth.instance.verifyPhoneNumber(
      verificationCompleted: (PhoneAuthCredential credential) {
        pinController.setText(credential.smsCode);
      },
      verificationFailed: (FirebaseAuthException e) {},
      codeSent: (String verificationId, int? resendToken) {},
      codeAutoRetrievalTimeout: (String verificationId) {},
    );
```

**Comment by Tkko** [comment]
Closing the issue for now because of inactivity, feel free to reopen it if you have the same problem.
