### ISSUE TITLE
Consider replacing FocusTrapArea

### ISSUE THREAD

**Issue by KristijanZic** [Tkko/Flutter_Pinput#116]
The next version of Flutter removes the FocusTrapArea widget. I'm not sure if flutter team made a replacement for it. In any case consider replacing it with another solution.

Testing Flutter_Pinput with Flutter beta channel crashes the build and produces the following error:
```
: Error: The method 'FocusTrapArea' isn't defined for the class '_PinputState'.
../…/src/pinput_state.dart:339
- '_PinputState' is from 'package:pinput/src/pinput.dart' ('../../../.pub-cache/hosted/pub.dev/pinput-2.2.21/lib/src/pinput.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FocusTrapArea'.
      child: FocusTrapArea(
             ^^^^^^^^^^^^^
```

**Comment by Tkko** [comment]
Hey @KristijanZic, that's a well known [issue](https://github.com/Tkko/Flutter_Pinput/issues/98)

Here is the patch and you can directly depend on it if you don't want to use Flutter's stable channel.
```
  pinput:
   git:
    url: https://github.com/Tkko/Flutter_Pinput
    ref: dev 
```

Once Flutter team removes FocusTrapArea from stable I'll merge dev branch to master.

**Comment by KristijanZic** [comment]
FocusTrapArea has been removed from stable yesterday.

**Comment by enriquejuan2** [comment]
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (30 hours ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1

I am on the above version of flutter and FocusTrapArea has been removed in the stable so kindly consider replacing it.

**Comment by Tkko** [comment]
Hey guys, the update will be ready in couple of minutes

**Comment by nicks258** [comment]
Thanks for prompt response. Please update as soon as possible.

**Comment by abdulla-bey01** [comment]
> Hey guys, the update will be ready in couple of minutes

I got this error on ci-azure deploy, but when i build appbundle on my pc, there is no problem. will this be able to be fixed?

**Comment by sds-dipak** [comment]
Still has issue of **FocusTrapArea** on pinput version `2.2.21`.

But the given patch working fine.

```yaml
 pinput:
   git:
    url: https://github.com/Tkko/Flutter_Pinput
    ref: dev 
```

**Comment by Tkko** [comment]
Here you go guys, the update is live on pub
[Version 2.2.22](https://pub.dev/packages/pinput)

**Comment by AliKarimiENT** [comment]
I don't know while I have added pinput with git, url and ref
but I'm getting this errors

![image](https://user-images.githubusercontent.com/57004354/215743715-ffd972ae-fee7-4723-ab9b-eb9871304ea0.png)

**Comment by Tkko** [comment]
Hey @AliKarimiENT, this error is't related to this issue, please create a new issue and provide
- Error logs
- flutter --version
- Did you change anything in `android/app/build.gradle` ?
- Did you change anything in  `android/build.gradle` ?

**Comment by kamami** [comment]
Because project depends on pinput >=2.2.23 which requires Flutter SDK version >=3.7.0, version solving failed.
I am currently on the beta channel 3.7.0-1.5.pre

Shouldn't it be working there?

**Comment by Tkko** [comment]
Hey @kamami I know it's  bit late but do you have the same issue?
