### ISSUE TITLE
pinput tries to listen to sms while running on mobile browser

### ISSUE THREAD

**Issue by tonis2** [Tkko/Flutter_Pinput#117]
I'm getting this error while running my flutter app on mobile web browser.

`Pinput/SmartAuth: getSmsCode failed: MissingPluginException(No implementation found for method startSmsUserConsent on channel fman.smart_auth)`

Can I somehow disable the sms listener manually ? For example I would check if its running on web and screen size < 600

**Comment by Tkko** [comment]
Check if the app is running on the Web and set androidSmsAutofillMethod: AndroidSmsAutofillMethod.none

**Comment by tonis2** [comment]
Okay, yep this line did the trick

` androidSmsAutofillMethod: kIsWeb ? AndroidSmsAutofillMethod.none : AndroidSmsAutofillMethod.smsUserConsentApi,`

**Comment by Tkko** [comment]
@tonis2 I've added correct platform check inside Pinput so you don't have to check it on your side.

Note that the latest version requires Flutter 3.7.0
