### ISSUE TITLE
v2.2.22 fails to build using Flutter 3.3.10

### ISSUE THREAD

**Issue by techouse** [Tkko/Flutter_Pinput#119]
```
Xcode's output:
↳
Writing result bundle at path:
/var/folders/yv/8w6xq4fn78n0vkhbx_0kb7b1vd3hvp/T/flutter_tools.zjQuuS/flutter_ios_build_temp_dirG67sz0/temporary_xcresult_bundle

    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: Type 'EditableTextContextMenuBuilder' not found.
      final EditableTextContextMenuBuilder? contextMenuBuilder;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: Type 'TapRegionCallback' not found.
      final TapRegionCallback? onTapOutside;
            ^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: 'EditableTextContextMenuBuilder' isn't a type.
      final EditableTextContextMenuBuilder? contextMenuBuilder;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: 'TapRegionCallback' isn't a type.
      final TapRegionCallback? onTapOutside;
            ^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:363:12: Error: Undefined name 'AdaptiveTextSelectionToolbar'.
        return AdaptiveTextSelectionToolbar.editableText(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:727:27: Error: 'EditableTextContextMenuBuilder' isn't a type.
          DiagnosticsProperty<EditableTextContextMenuBuilder?>(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:354:16: Error: The method 'TextFieldTapRegion' isn't defined for the class '_PinputState'.
     - '_PinputState' is from 'package:pinput/src/pinput.dart' ('/usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'TextFieldTapRegion'.
            return TextFieldTapRegion(
                   ^^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:444:11: Error: No named parameter with the name 'contextMenuBuilder'.
              contextMenuBuilder: widget.contextMenuBuilder,
              ^^^^^^^^^^^^^^^^^^
    /usr/local/Caskroom/flutter/3.3.10/flutter/packages/flutter/lib/src/widgets/editable_text.dart:572:3: Context: Found this candidate, but the arguments don't match.
      EditableText({
      ^^^^^^^^^^^^
    Failed to package /Users/techouse/Work/myApp.
```

**Comment by keblato** [comment]
Hi 👋  i have the same problem 

../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: Type 'EditableTextContextMenuBuilder' not found.
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: Type 'TapRegionCallback' not found.
  final TapRegionCallback? onTapOutside;
        ^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: 'EditableTextContextMenuBuilder' isn't a type.
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: 'TapRegionCallback' isn't a type.
  final TapRegionCallback? onTapOutside;
        ^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:363:12: Error: Undefined name 'AdaptiveTextSelectionToolbar'.
    return AdaptiveTextSelectionToolbar.editableText(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:727:27: Error: 'EditableTextContextMenuBuilder' isn't a type.
      DiagnosticsProperty<EditableTextContextMenuBuilder?>(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:354:16: Error: The method 'TextFieldTapRegion' isn't defined for the class '_PinputState'.
 - '_PinputState' is from 'package:pinput/src/pinput.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextFieldTapRegion'.
        return TextFieldTapRegion(
               ^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:444:11: Error: No named parameter with the name 'contextMenuBuilder'.
          contextMenuBuilder: widget.contextMenuBuilder,
          ^^^^^^^^^^^^^^^^^^
../../../../fvm/versions/3.3.9/packages/flutter/lib/src/widgets/editable_text.dart:572:3: Context: Found this candidate, but the arguments don't match.
  EditableText({

**Comment by enriquejuan2** [comment]
> Hi 👋 i have the same problem
> 
> ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: Type 'EditableTextContextMenuBuilder' not found. final EditableTextContextMenuBuilder? contextMenuBuilder; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: Type 'TapRegionCallback' not found. final TapRegionCallback? onTapOutside; ^^^^^^^^^^^^^^^^^ ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: 'EditableTextContextMenuBuilder' isn't a type. final EditableTextContextMenuBuilder? contextMenuBuilder; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: 'TapRegionCallback' isn't a type. final TapRegionCallback? onTapOutside; ^^^^^^^^^^^^^^^^^ ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:363:12: Error: Undefined name 'AdaptiveTextSelectionToolbar'. return AdaptiveTextSelectionToolbar.editableText( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:727:27: Error: 'EditableTextContextMenuBuilder' isn't a type. DiagnosticsProperty<EditableTextContextMenuBuilder?>( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:354:16: Error: The method 'TextFieldTapRegion' isn't defined for the class '_PinputState'.
> 
> * '_PinputState' is from 'package:pinput/src/pinput.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'TextFieldTapRegion'.
>   return TextFieldTapRegion(
>   ^^^^^^^^^^^^^^^^^^
>   ../../../../.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:444:11: Error: No named parameter with the name 'contextMenuBuilder'.
>   contextMenuBuilder: widget.contextMenuBuilder,
>   ^^^^^^^^^^^^^^^^^^
>   ../../../../fvm/versions/3.3.9/packages/flutter/lib/src/widgets/editable_text.dart:572:3: Context: Found this candidate, but the arguments don't match.
>   EditableText({

I have successfully built version 2.2.22, all you need to do is to update to the latest stable version of flutter which is 3.7, contextMenuBuilder replaces ToolbarOptions in the latest version of flutter. Hope this helps

**Comment by enriquejuan2** [comment]
> ```
> Xcode's output:
> ↳
> Writing result bundle at path:
> /var/folders/yv/8w6xq4fn78n0vkhbx_0kb7b1vd3hvp/T/flutter_tools.zjQuuS/flutter_ios_build_temp_dirG67sz0/temporary_xcresult_bundle
> 
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: Type 'EditableTextContextMenuBuilder' not found.
>       final EditableTextContextMenuBuilder? contextMenuBuilder;
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: Type 'TapRegionCallback' not found.
>       final TapRegionCallback? onTapOutside;
>             ^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:349:9: Error: 'EditableTextContextMenuBuilder' isn't a type.
>       final EditableTextContextMenuBuilder? contextMenuBuilder;
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:357:9: Error: 'TapRegionCallback' isn't a type.
>       final TapRegionCallback? onTapOutside;
>             ^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:363:12: Error: Undefined name 'AdaptiveTextSelectionToolbar'.
>         return AdaptiveTextSelectionToolbar.editableText(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart:727:27: Error: 'EditableTextContextMenuBuilder' isn't a type.
>           DiagnosticsProperty<EditableTextContextMenuBuilder?>(
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:354:16: Error: The method 'TextFieldTapRegion' isn't defined for the class '_PinputState'.
>      - '_PinputState' is from 'package:pinput/src/pinput.dart' ('/usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput.dart').
>     Try correcting the name to the name of an existing method, or defining a method named 'TextFieldTapRegion'.
>             return TextFieldTapRegion(
>                    ^^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-2.2.22/lib/src/pinput_state.dart:444:11: Error: No named parameter with the name 'contextMenuBuilder'.
>               contextMenuBuilder: widget.contextMenuBuilder,
>               ^^^^^^^^^^^^^^^^^^
>     /usr/local/Caskroom/flutter/3.3.10/flutter/packages/flutter/lib/src/widgets/editable_text.dart:572:3: Context: Found this candidate, but the arguments don't match.
>       EditableText({
>       ^^^^^^^^^^^^
>     Failed to package /Users/techouse/Work/myApp.
> ```

I have successfully built version 2.2.22, all you need to do is to update to the latest stable version of flutter which is 3.7, contextMenuBuilder replaces ToolbarOptions in the latest version of flutter. Hope this helps

**Comment by enriquejuan2** [comment]
I have successfully built version 2.2.22, all you need to do is to update to the latest stable version of flutter which is 3.7, contextMenuBuilder replaces ToolbarOptions in the latest version of flutter. Hope this helps

**Comment by Tkko** [comment]
You have to upgrade flutter to 3.7 or use Pinput version 2.2.21, hope this helps.

**Comment by techouse** [comment]
Shouldn't it then have some sort of constraint preventing the user to upgrade to 2.2.22 if they don't yet have Flutter 3.7.0 but have `pinput: ^2.2.21` in their pubspec.yaml?

Maybe this warrants a new major version, i.e. 3.0 if that's the case.

**Comment by Tkko** [comment]
> Shouldn't it then have some sort of constraint preventing the user to upgrade to 2.2.22 if they don't yet have Flutter 3.7.0 but have `pinput: ^2.2.21` in their pubspec.yaml?
> 
> Maybe this warrants a new major version, i.e. 3.0.

That's a good idea, let me check what can I do

**Comment by Tkko** [comment]
I've added the correct constraints and pushed the update.

**Comment by RaghuMudem** [comment]
> You have to upgrade flutter to 3.7 or use Pinput version 2.2.21, hope this helps.
**In short:** 
`Pinput version 2.2.21` does not work.
**Story:**
Using Pinput  2.2.21 and the Flutter version 3.3.10 does not work for me. For some reason, even if I gave `pinput: ^2.2.21` in the yaml file, still it try to compile the `pinput: ^2.2.22` . Please check the image below.

I already tried popular commands: `flutter clean`, `pub get`, `pub upgarde `and `flutter pub cache clean`. Still some reason, It my app gives the error as shown in the image.

![image](https://user-images.githubusercontent.com/42538820/214602174-e046d62f-763f-4cbe-abc4-8483ecbd98c4.png)

**Comment by Tkko** [comment]
@keblato Which flutter version are you using?

**Comment by Tkko** [comment]
Requested removing of version 2.2.22 from pub, in order to prevent more people updating from unsupported flutter version.

**Comment by RaghuMudem** [comment]
> @keblato Which flutter version are you using? If it's below 3.7.0
> 
> * The easy manual solution is to delete`../pub/cache/hosted/pub.dartlang.org/pinput-2.2.22` and run `flutter pub get`
> * Or run `flutter pub cache repair`

I confirm this is not working. 
With the Pinput version 2.2.21 and the flutter version 3.3.10. 

Whatever version you give in yaml file, it downloads the pinput 2.2.22 only. I already checked for using 2.2.21 and 2.2.16. Both are fetching the pinput 2.2.22.

**Comment by ashish-d-hh** [comment]
Yep facing issue

**Comment by Tkko** [comment]
Here is the plan B, guys I'm sorry for the inconvenience

Depend directly on version 2.2.1 from git
```
  pinput:
   git:
    url: https://github.com/Tkko/Flutter_Pinput
    ref: 2.2.21
```

**Comment by ashish-d-hh** [comment]
'FocusTrapArea'
`Running Gradle task 'assembleDebug'...
../.pub-cache/git/Flutter_Pinput-198b7ab6243705a9e008144ed2ae4d74e2c4c700/lib/src/pinput_state.dart:339:14: Error: The method 'FocusTrapArea' isn't defined for the class '_PinputState'.
 - '_PinputState' is from 'package:pinput/src/pinput.dart' ('../.pub-cache/git/Flutter_Pinput-198b7ab6243705a9e008144ed2ae4d74e2c4c700/lib/src/pinput.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FocusTrapArea'.
      child: FocusTrapArea(
             ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/netsmartz/Documents/DevApps/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/netsmartz/Documents/DevApps/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 24s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by Tkko** [comment]
@ashish-d-hh FYI this is an another issue, you have to use Pinput 2.2.23

**Comment by RaghuMudem** [comment]
> Guys I'm sorry for the inconvenience, here is the plan B:
> 
> Depend directly on version 2.2.1 from git
> 
> ```
>   pinput:
>    git:
>     url: https://github.com/Tkko/Flutter_Pinput
>     ref: 2.2.21
> ```
> 
> Confirm if it works.

Yes,

This could be the solution for the previous version's of flutter SDK( less than 3.7.0).

Thankyou

**Comment by Tkko** [comment]
@RaghuMudem Thanks you for confirmation, the pub.dev team will soon remove broken version (2.2.22) as well and issue will be solved.

We are getting closer to the end of the crisis 😃.

**Comment by Tkko** [comment]
Version 2.2.22 has been removed from pub.dev and `flutter pub get` won't fetch incorrect version 🤘
