### ISSUE TITLE
Add the ability to change enableIMEPersonalizedLearning

### ISSUE THREAD

**Issue by Coloud1** [Tkko/Flutter_Pinput#121]
Hi, @Tkko

Could you add the ability to set the enableIMEPersonalizedLearning parameter in a future release? This is due to the fact that our keyboard becomes incognito mode (Android 10, Samsung Galaxy S8) and we would like this mode to not be.

With enableIMEPersonalizedLearning: true

<img width="527" alt="image" src="https://user-images.githubusercontent.com/25287821/215480173-a917ae42-c9a6-48db-99cd-4e9339829968.png">
 
With enableIMEPersonalizedLearning: false

<img width="426" alt="image" src="https://user-images.githubusercontent.com/25287821/215480307-2b709506-234d-4879-a33f-a01e013c3106.png">

In a Material TextField, Flutter provides the ability to change this property (which is true by default)

https://developer.android.com/reference/android/view/inputmethod/EditorInfo#IME_FLAG_NO_PERSONALIZED_LEARNING

**Comment by Tkko** [comment]
@Coloud1 `enableIMEPersonalizedLearning` is false by default? Do you want it to be true?
https://github.com/Tkko/Flutter_Pinput/blob/856c8d5c102d751ac345a6122f244c7702d29250/lib/src/pinput_state.dart#L419

**Comment by Tkko** [comment]
@Coloud1 I thought no one would need `enableIMEPersonalizedLearning: true` but sure, I'll add it.

**Comment by Coloud1** [comment]
Ok, thanks a lot

**Comment by Coloud1** [comment]
Hello, @Tkko . I hope you haven't forgotten about me. This thread is still relevant to me

**Comment by Tkko** [comment]
Hey @Coloud1, just pushed the update with the `enableIMEPersonalizedLearning` property
https://pub.dev/packages/pinput/changelog

**Comment by Coloud1** [comment]
Thank you very much, @Tkko . Have a nice day
