### ISSUE TITLE
how to show cursor  when i write pin

### ISSUE THREAD

**Issue by thewama33** [Tkko/Flutter_Pinput#122]
while typing  the cursor disapears how to avoid that and show cursor even when i type pins

**Comment by Tkko** [comment]
What do you mean cursor disappear? is is animating (fading in/out) if yes  you can set `isCursorAnimationEnabled` to `false`. If it's something else please provide small reproducible code snippet and video.

**Comment by thewama33** [comment]
https://ibb.co/pWpVyBz   

here under the numbers i type   the cursor disapears  
i want to keep cursor under the numbers when i type

**Comment by Tkko** [comment]
Well, I'm planning to add `Pinput.builder` constructor for more customizations, I can't tell you for sure but if it might include such feature.

**Comment by Tkko** [comment]
The `Pinput.builder` is available in versions ^5.0.0 so you can show anything in any pin at anytime.
