### ISSUE TITLE
Could not resolve project :smart_auth.

### ISSUE THREAD

**Issue by pr-1** [Tkko/Flutter_Pinput#123]
I just upgraded to flutter 3.7 and pinput 2.2.23. Cannot Build release app bundle It gives me the following error 

```dart

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:minifyStagReleaseWithR8'.
> Could not resolve all task dependencies for configuration ':app:stagReleaseCompileClasspath'.
   > Could not resolve project :smart_auth.
     Required by:
         project :app
      > No matching configuration of project :smart_auth was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'default' with value 'stag', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

```

I am using the default config of ```AndroidSmsAutofillMethod.none ```
It is working like a charm on ios though. Is there something extra I need to do in manifest ?

Flutter doctor - 
```dart
princesrivastava@Princes-MacBook-Pro ExplO-Frontend % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by pr-1** [comment]
I am not using firebase for auto fill

**Comment by Tkko** [comment]
Hey @pr-1, I suppose you already tried `flutter clean`, is that correct?

Could you share the snippets of `android/build.gradle` and `android/app/build.gradle`? it has to be some kind of versioning issue

Also, linking some topics that might solve the problem
https://stackoverflow.com/questions/34421193/could-not-determine-the-dependencies-of-task-appcrashlyticsstoredeobsdebug-i

https://stackoverflow.com/questions/59476081/flutter-error-could-not-determine-the-dependencies-of-task-appcompiledebugjav

**Comment by pr-1** [comment]
Hey @Tkko  Thanks for the response. Yes I tried flutter clean and even removing older versions from my global pub cache manually. 
I tried to recreate the issue on a base project without product flavors and it worked smooth. 
It might be the case that since I am using product flavors on my app it is causing some issues in configuration. I will come back with a reproducible sample with product flavors over next weekend. We can close this as Not Planned till then if you want.
For now I have removed the package and it is working fine. I tried the stackoverflow links that you have shared but it did not work.

**Comment by Tkko** [comment]
`SmartAuth` was removed from Pinput in versions ^5.0.0, so that I don't force people who don't want to use SMS autofill to depend on it and avoid building issue like this.

If you need the SMS autofill on android and still having same issue, please checkout the [SmartAuth](https://github.com/Tkko/flutter_smart_auth) repo.
