### ISSUE TITLE
Could not run project successfully  due to void onDoubleTapDown(TapDownDetails details)  method argument type

### ISSUE THREAD

**Issue by tariqali786** [Tkko/Flutter_Pinput#124]
/C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/pinput-2.2.23/lib/src/widgets/_pinput_selection_gesture_detector_builder.dart:20:39: **Error: The parameter 'details' of the method '_PinputSelectionGestureDetectorBuilder.onDoubleTapDown' has type 'TapDownDetails', which does not match the corresponding type, 'TapDragDownDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onDoubleTapDown'.**
 - 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('/C:/Users/User/flutter/packages/flutter/lib/src/gestures/tap.dart').
 - 'TapDragDownDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('/C:/Users/User/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
Change to a supertype of 'TapDragDownDetails', or, for a covariant parameter, a subtype.
  void onDoubleTapDown(TapDownDetails details) {
                                      ^
/C:/Users/User/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2431:8: Context: This is the overridden method ('onDoubleTapDown').
  void onDoubleTapDown(TapDragDownDetails details) {
       ^
/C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/pinput-2.2.23/lib/src/widgets/_pinput_selection_gesture_detector_builder.dart:27:35: Error: The parameter 'details' of the method '_PinputSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
 - 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('/C:/Users/User/flutter/packages/flutter/lib/src/gestures/tap.dart').
 - 'TapDragUpDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('/C:/Users/User/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
Change to a supertype of 'TapDragUpDetails', or, for a covariant parameter, a subtype.
  void onSingleTapUp(TapUpDetails details) {
                                  ^
/C:/Users/User/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2144:8: Context: This is the overridden method ('onSingleTapUp').
  void onSingleTapUp(TapDragUpDetails details) {
       ^
/C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/pinput-2.2.23/lib/src/widgets/_pinput_selection_gesture_detector_builder.dart:28:25: **Error: The argument type 'TapUpDetails' can't be assigned to the parameter type 'TapDragUpDetails'.**
 - 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('/C:/Users/User/flutter/packages/flutter/lib/src/gestures/tap.dart').
 - 'TapDragUpDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('/C:/Users/User/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
    super.onSingleTapUp(details);
                        ^

After changing the method arguments in package class
**From**
@override
  void onDoubleTapDown(TapDownDetails details) {
    if (shouldShowSelectionToolbar) {
      editableText.showToolbar();
    }
  }

  @override
  void onSingleTapUp(TapUpDetails details) {
    super.onSingleTapUp(details);
    editableText.hideToolbar();
    _state._requestKeyboard();
    _state.widget.onTap?.call();
  }

**To** 

  @override
  void onDoubleTapDown(TapDragDownDetails details) {
    if (shouldShowSelectionToolbar) {
      editableText.showToolbar();
    }
  }

  @override
  void onSingleTapUp(TapDragUpDetails details) {
    super.onSingleTapUp(details);
    editableText.hideToolbar();
    _state._requestKeyboard();
    _state.widget.onTap?.call();
  }

after that I successfully run the project . Please solve this in package or guide me what I am missing.

**Comment by Tkko** [comment]
Hey @tariqali786, could you share the output of the `flutter --version`

**Comment by tariqali786** [comment]
Flutter 3.8.0-9.0.pre.1 • channel master • https://github.com/flutter/flutter.git
Framework • revision b1c4d5686e (5 days ago) • 2023-02-08 16:55:05 -0800
Engine • revision 89c8a1393d
Tools • Dart 3.0.0 (build 3.0.0-215.0.dev) • DevTools 2.21.1

**Comment by Tkko** [comment]
Is is possible to switch to the stable channel? 
It seems like the `TapDragDownDetails` is newly added in the Flutter's master branch

**Comment by teewhydope** [comment]
same issue. i think i need to downgrade

**Comment by Tkko** [comment]
Switching to Flutter's stable channel will solve the issue, meanwhile I'll align my code to Flutter's master branch and let you know

**Comment by raldhafiri** [comment]
I have a simple solution to made it work on both stable and master channel
https://github.com/raldhafiri/Flutter_Pinput.git

solution was by changing "TapDownDetails" and "TapUpDetails" to "dynamic"

**Comment by Tkko** [comment]
BTW guys why do you use the master channel?

**Comment by raldhafiri** [comment]
I am working in big project and we are using this amazing package .. we build and test for both channels

**Comment by teewhydope** [comment]
> BTW guys why do you use the master channel?

To test out dart 3.0 features

**Comment by Tkko** [comment]
Pushed the update
Version [2.2.30](https://pub.dev/packages/pinput/versions/2.2.30)

**Comment by raldhafiri** [comment]
Thanks and much appericated

**Comment by teewhydope** [comment]
Thanks for the quick fix

**Comment by tariqali786** [comment]
Thank you!
