### ISSUE TITLE
How to use golden_toolkit with flutter_pinput?

### ISSUE THREAD

**Issue by abhishek-trigsy** [Tkko/Flutter_Pinput#125]
I'm trying to write golden tests using golden_toolkit(https://pub.dev/packages/golden_toolkit), but it is throwing "pumpAndSettle timed out" exception.
`testGoldens(
    'VerifyMobileNumber Golden Test',
    (tester) async {
      // Builds the given scenario within a device wrapper
      final builder = DeviceBuilder()
        ..addScenario(
          name: 'Verify Mobile OTP',
          widget: const ProviderScope(
            child: VerifyMobileOtpScreen(
              phoneNumber: '1234561234',
            ),
          ),
        );

      await tester.pumpDeviceBuilder(
        builder,
        wrapper: materialAppWrapper(
          theme: lightTheme(),
        ),
      );

      await screenMatchesGolden(tester, 'verify_mob_otp_screen');
    },
  );`

**Comment by Tkko** [comment]
Hey @abhishek-trigsy try to set `isCursorAnimationEnabled` to false while running the test

**Comment by abhishek-trigsy** [comment]
Thanks @Tkko it worked. Would try to make it false by overriding it using a provider for the tests.
