### ISSUE TITLE
[Autofill] do not receive signature in sms

### ISSUE THREAD

**Issue by ddicko** [Tkko/Flutter_Pinput#127]
I do not receive a signature [10 characters] in the sms, will there be a config to do on the firebase side?.
can someone enlighten me?

**Comment by Tkko** [comment]
If you are using firebase_auth
set `androidSmsAutofillMethod` to none and set controller's value in verificationCompleted:
``` dart
    Pinput(
      androidSmsAutofillMethod: AndroidSmsAutofillMethod.none,
      controller: pinController,
    );
```
And set pinController's value in `verificationCompleted` callback:
``` dart
    await FirebaseAuth.instance.verifyPhoneNumber(
      verificationCompleted: (PhoneAuthCredential credential) {
        pinController.setText(credential.smsCode);
      },
      verificationFailed: (FirebaseAuthException e) {},
      codeSent: (String verificationId, int? resendToken) {},
      codeAutoRetrievalTimeout: (String verificationId) {},
    );
```

The firebase_auth handles automatic SMS resolution on it's own and if you turn on Pinput's androidSmsAutofillMethod it both plugin is trying to read SMS and app crashes.

**Comment by Tkko** [comment]
Closing the issue for now because of inactivity, feel free to reopen it if you have the same problem.
