### ISSUE TITLE
Can't get smsUserConsentApi to work on Android

### ISSUE THREAD

**Issue by abdullah10182** [Tkko/Flutter_Pinput#130]
Hi, 

I've been trying to get the smsUserConsentApi method to work with no luck. The dialog does not show.

I run the example app on my phone and it works as it should. I've copied the whole "PinputExample" widget from the example app into my app and still cannot get it to work.

Am I missing something on the Android side or something? I've checked the manifest file but can't find anything in particular.

Any help would be appreciated, thanks.

**Comment by Tkko** [comment]
Hey @abdullah10182, Are you using Firebase auth?

**Comment by abdullah10182** [comment]
No, I'm using app_auth with custom authentication.

But I am using firebase analytics wich requires firebase_analytics and firebase_core.

**Comment by Tkko** [comment]
I can't find the package named app_auth, could you give me the pub link

**Comment by abdullah10182** [comment]
it's this one:
https://pub.dev/packages/flutter_appauth

**Comment by Tkko** [comment]
I don't see any problem with that package, is there any error printed in the console?

**Comment by abdullah10182** [comment]
I basically removed every lib from my app and got it to work. 

I'm gonna spend the rest of the day trying to figure out what is causing the issue. Will follow up and let you know what is causing it. 

Thanks

**Comment by abdullah10182** [comment]
Is there a way to trigger the sms listener manually? I use riverpod which uses watchers, and noticed every time I have listeners in a widget it does not work. Although I've tried to import riverpod in the example app and it works perfectly. So not sure what it might be.

So the only thing I can think of now is to start the listener manually after all watchers have been loaded.

**Comment by Tkko** [comment]
Hey @abdullah10182, sorry for the late reply, you can start listening by manually by using SmartAuth class, it's exported from the Pinput so you don't have to add plugin manually.
```dart
    final smartAuth = SmartAuth();
    final res = await smartAuth.getSmsCode();
```

**Comment by Tkko** [comment]
Closing the issue for now, feel free to reopen if needed.
