### ISSUE TITLE
Error Receiving Broadcast Intent 

### ISSUE THREAD

**Issue by faisalmushtaq007** [Tkko/Flutter_Pinput#131]
i am using the latest version of pinput package and when i verify the phone number and move to otp screen. I minimize the app for getting otp and when i return to app it crashes with the following error:
"
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.lelafe.psajk (has extras) } in com.google.android.gms.internal.firebase-auth-api.zzyt@207799d
E/AndroidRuntime( 5801): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1928)
"

**Comment by Tkko** [comment]
Closing the issue for now, feel free to reopen if needed.
