### ISSUE TITLE
bottom Cursor

### ISSUE THREAD

**Issue by Higher-Soft** [Tkko/Flutter_Pinput#134]
### How do I implement this??
Does anyone have a solution?

@Tkko @xportation @almeynman @ALL 
![image](https://user-images.githubusercontent.com/128693457/236158273-5fb2b8c7-10a2-404a-80b2-0fdc41d06776.png)

**Comment by Tkko** [comment]
Hey @Higher-Soft, here is the [template code](https://github.com/Tkko/Flutter_Pinput/blob/master/example/lib/demo/pinput_templates/only_bottom_cursor.dart)
