### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe

### ISSUE THREAD

**Issue by afelipe00** [Tkko/Flutter_Pinput#139]
**Describe the bug**
I am using the widget as shown in the example, when I try to enter the first number of the pinfield it tells me that I am losing reference to a parent widget, I guess it is because the dispose is being called where it should not be.

**Screenshots**
════════ Exception caught by widgets library ═══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

**Pinput version:** 2.2.31

**Result of:** `flutter doctor --verbose`
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale es-CO)
    • Flutter version 3.10.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (4 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\afeli\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • VS Code at C:\Users\afeli\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • SM A525M (mobile) • R58RC09HK0W • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 114.0.5735.90
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 113.0.1774.50

[✓] Network resources
    • All expected network resources are available.

• No issues found!
...
</details>

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s21
 - OS: Android 13

**Comment by Tkko** [comment]
Hey @afelipe00, could you provide the code snippet?

**Comment by afelipe00** [comment]
sure! I already provide you the code, I am trying to debug to have a little more precision with the reason of the possible bug.


class VerifyCodePage extends StatefulWidget {
  const VerifyCodePage({super.key});

  @override
  State<VerifyCodePage> createState() => _VerifyCodePageState();
}

class _VerifyCodePageState extends State<VerifyCodePage> {
  final pinController = TextEditingController();
  late FocusNode focusNode;
  final formKey = GlobalKey<FormState>();

  @override
  void initState() {
    focusNode = FocusNode();
    super.initState();
  }

  @override
  void dispose() {
    pinController.dispose();
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;
    final ColorScheme colors = Theme.of(context).colorScheme;
    final UserBloc userBloc = BlocProvider.of<UserBloc>(context);

    Widget header = SizedBox(
      height: size.height * 0.40,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          SizedBox(
            height: size.height * .2,
            width: size.width,
            child: Image.asset(
              MyImages.logoMyLightRed,
              fit: BoxFit.fitWidth,
            ),
          ),
          const SizedBox(
            height: 10.0,
          ),
          const Padding(
            padding: EdgeInsets.all(8.0),
            child: Text(
              'Código de verificación',
              style: TextStyle(
                fontFamily: 'Boston',
                fontWeight: FontWeight.bold,
                fontSize: 20.0,
              ),
            ),
          ),
          const Padding(
            padding: EdgeInsets.all(8.0),
            child: Text(
              'Ingresar el código enviado a userInfo',
              style: TextStyle(
                fontFamily: 'Boston',
                fontWeight: FontWeight.normal,
                fontSize: 14.0,
              ),
            ),
          )
        ],
      ),
    );

    PinTheme pinTheme = PinTheme(
      width: 56,
      height: 56,
      textStyle: const TextStyle(
        fontSize: 22,
        color: Color.fromRGBO(30, 60, 87, 1),
      ),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(19),
        border: Border.all(color: Color.fromRGBO(23, 171, 144, 0.4)),
      ),
    );

    Widget pinForm = Form(
      key: formKey,
      child: Column(
        children: [
          Directionality(
            textDirection: TextDirection.ltr,
            child: Pinput(
              length: 6,
              controller: pinController,
              focusNode: focusNode,
              hapticFeedbackType: HapticFeedbackType.lightImpact,
              cursor: Column(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  Container(
                    margin: const EdgeInsets.only(bottom: 9),
                    width: 22,
                    height: 1,
                    color: Colors.red,
                  ),
                ],
              ),
              validator: (value) {
                return value == '222222' ? null : 'Pin is incorrect';
              },
              defaultPinTheme: pinTheme,
              focusedPinTheme: pinTheme.copyWith(
                decoration: pinTheme.decoration!.copyWith(
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Color.fromRGBO(23, 171, 144, 1)),
                ),
              ),
              submittedPinTheme: pinTheme.copyWith(
                decoration: pinTheme.decoration!.copyWith(
                  color: Color.fromRGBO(243, 246, 249, 0),
                  borderRadius: BorderRadius.circular(19),
                  border: Border.all(color: Color.fromRGBO(23, 171, 144, 1)),
                ),
              ),
              errorPinTheme: pinTheme.copyBorderWith(
                border: Border.all(color: Colors.redAccent),
              ),
            ),
          ),
        ],
      ),
    );

    return Container(
      color: colors.background,
      child: Stack(
        children: [
          Scaffold(
            appBar: AppBar(
              leading: IconButton(
                icon: const Icon(Icons.arrow_back),
                onPressed: () {
                  userBloc.add(SignUpEvent(user: User(), reverseTransition: true));
                },
              ),
              actions: [
                Padding(
                  padding: const EdgeInsets.all(5.0),
                  child: IconButton(
                    icon: Icon(
                      Icons.help_rounded,
                      color: colors.primary,
                    ),
                    onPressed: () {},
                    style: IconButton.styleFrom(
                      side: BorderSide(color: Theme.of(context).colorScheme.onBackground.withOpacity(0.12)),
                      highlightColor: colors.onSecondaryContainer.withOpacity(0.12),
                    ),
                  ),
                ),
              ],
              centerTitle: true,
              title: SizedBox(
                width: size.width * 0.17,
                child: Image.asset(
                  MyImages.logoMyWhite,
                  color: colors.primary,
                  fit: BoxFit.fitWidth,
                ),
              ),
            ),
            body: SafeArea(
              child: SingleChildScrollView(
                child: Column(
                  children: [
                    header,
                    const SizedBox(
                      height: 20.0,
                    ),
                    pinForm,
                    const SizedBox(
                      height: 12.0,
                    ),
                    RichText(
                      text: TextSpan(
                        text: "¿No recibiste el código? ",
                        style: TextStyle(
                          fontFamily: "Boston",
                          color: colors.onBackground,
                        ),
                        children: [
                          TextSpan(
                            text: " Reenviar",
                            style: TextStyle(fontFamily: "Boston", color: colors.primary),
                            recognizer: TapGestureRecognizer(),
                          )
                        ],
                      ),
                    ),
                    const SizedBox(
                      height: 50.0,
                    ),
                    Padding(
                      padding: const EdgeInsets.all(10.0),
                      child: ElevatedButton(
                        onPressed: () {},
                        style: ElevatedButton.styleFrom(
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.0))),
                        child: const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 30.0),
                          child: Text("Verificar"),
                        ),
                      ),
                    )
                  ],
                ),
              ),
            ),
            floatingActionButton: FloatingActionButton(onPressed: () {
              userBloc.add(VerifySmsCodeEvent(pin: '1234', orc: Orchestrator()));
            }),
          ),
          const DialogManagerPage(),
        ],
      ),
    );
  }
}

**Comment by afelipe00** [comment]
I have not managed to find the point where the bug is generated but well, here I put screenshots of the error that is shown to me. This happens when I interact with the pinInput, either entering a number or deleting it.

![image](https://github.com/Tkko/Flutter_Pinput/assets/47798722/6194eda3-5a13-4310-b6a6-037db5f3228e)

![image](https://github.com/Tkko/Flutter_Pinput/assets/47798722/b9bc863e-61a1-40f2-bd1d-705c57701d4e)

**Comment by Tkko** [comment]
Hey @afelipe00, sorry for the late response, I'm sure you solved the issue meantime so closing this one, feel free to reopen if needed.

**Comment by simonbrandhof** [comment]
Hi @iPypeNB I have the same issue. Did you find the workaround?

**Comment by simonbrandhof** [comment]
The problem comes from the order of calls in `dispose()`. It should be:
```dart
@override
  void dispose() {
    focusNode.dispose();
    pinController.dispose();
    super.dispose();
  }
  ```
