### ISSUE TITLE
[2.3.0] Unclear change log `default SMS code matcher regex length to 8 digits` how should I change my code to stay on 6 chars?

### ISSUE THREAD

**Issue by mariopepe** [Tkko/Flutter_Pinput#141]
The change log for a **potentially** (maybe? not sure? not clear?) **breaking** change is not clear.

Change log states: `Updated default SMS code matcher regex length to 8 digits`.

My OTPs are 6 chars, how should I change the code to keep the matcher length to 6 digits?

I tried to search in the commits history but none of the commits seems to be about that so I am not even sure how to find this information by myself (see screenshot)

Thanks

<img src="https://github.com/Tkko/Flutter_Pinput/assets/14803862/21b33a33-3c4e-4e92-92ce-2bf0c5dd9bf8"  width="30%">

**Comment by Tkko** [comment]
Hey @mariopepe, sorry for the inconvenience, from now on the default sms code matcher regex will match maximum 8 characters instead of 7, so you should be good to go.

**Comment by mariopepe** [comment]
Fantastic thanks to you!

**Comment by pawanDreemz** [comment]
@Tkko 
WDYT about, user can pass the custom matcher?

**Comment by devpawann** [comment]
@Tkko
WDYT about, user can pass the custom matcher?

**Comment by Tkko** [comment]
@devpawann you can pass it. The parameter is called `smsCodeMatcher`
