### ISSUE TITLE
Zoom issues on mobile Safari

### ISSUE THREAD

**Issue by chimon2000** [Tkko/Flutter_Pinput#144]
**Describe the bug**
While entering the verification code in mobile safari, the screen unexpectedly zooms in without any deliberate user action. This zooming effect may cause inconvenience or make it difficult to accurately input the code

**To Reproduce**
1. Go to a screen with a pinput
2. Select the first cell
3. Observe that the window has zoomed.

**Screenshots**
n/a

**Pinput version:** 2.3.0

**Result of:** `flutter doctor --verbose`
<details>
Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
</details>

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 16.6
 - Browser: Safari

**Additional context**

**Comment by Tkko** [comment]
Hey @chimon2000, can you verify that the issue exists on demo [web page](https://flutter_pinput.codemagic.app/)?
I didn't see any issue from my old iPhone XS (16.5.1)

**Comment by aqrc** [comment]
@Tkko for me it happens when app is inserted in the iframe. See the video attached

https://github.com/Tkko/Flutter_Pinput/assets/6764175/e6c58568-8ec2-40dc-97d8-fb96a378d9c3

**Comment by Tkko** [comment]
This issue is most likely out of my scope, If anyone knows how to fix it please create a PR or provide the solution and I'll add it, thanks.
