### ISSUE TITLE
keyboard  iOS

### ISSUE THREAD

**Issue by icc-tips** [Tkko/Flutter_Pinput#145]
length==4, when I input a word and click the completion button on the keyboard, the height of the input increases

**Comment by Tkko** [comment]
Hey @icc-tips, can you post the snippet of the code so that I can reproduce it on my machine?

**Comment by Tkko** [comment]
Since there has been no response or follow-up, I am closing this issue for now. If you still encounter the problem or need further assistance, feel free to reopen the issue or create a new one. Thank you!
