### ISSUE TITLE
How to custom paste button

### ISSUE THREAD

**Issue by ruslanouv2** [Tkko/Flutter_Pinput#146]
**Is your feature request related to a problem? Please describe.**
Hey i still searching for the custom the paste button. Is it possible?

**Comment by Tkko** [comment]
Hey @ruslanouv2, 

1. from version ^3.0.1 you can use `[contextMenuBuilder](https://api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html)` to customize the toolbar options.
2. You can set `toolbarEnabled` to `false` and pass `onLongPress` callback and then show your custom dialog
