### ISSUE TITLE
flutter web apple safari on the keyboard

### ISSUE THREAD

**Issue by mohamadhadibi** [Tkko/Flutter_Pinput#148]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mohamadhadibi** [comment]
is there anyway for web opened on iphone safari read sms on the keyboard or autofill?

**Comment by Aryan-Sood** [comment]
Hi @mohamadhadibi, did you find the solution for this issue of read sms in safari? I am also facing this issue currently.

**Comment by Tkko** [comment]
The code should pop up automatically on top of the keyboard. If not there might be the problem with the language and the format of the SMS. Try something like

`Your code is 1234`

**Comment by Tkko** [comment]
Since there has been no response or follow-up, I am closing this issue for now. If you still encounter the problem or need further assistance, feel free to reopen the issue or create a new one. Thank you!
