### ISSUE TITLE
Cursor is not shown on Pinput tap after completion.

### ISSUE THREAD

**Issue by MrLepage** [Tkko/Flutter_Pinput#152]
**Describe the bug**
Cursor is not shown on Pinput tap after completion.
To display the cursor, a backspace needs to be made after Pinput tap.

**To Reproduce**
1. Complete the Pinput
2. The keyboard is dismissed
3. Click on the Pinput -> Keyboard reappears but there is no cursor shown
4. Tap "back" on the keyboard
5. The cursor is now shown on the last PinItem

**Screenshots**
https://github.com/Tkko/Flutter_Pinput/assets/18703480/59725d3e-50fe-4dfd-8ca6-ad2233ecdb12

**Pinput version**
3.0.1

**Smartphone**
 - Device: iPhone 15 Pro
 - OS: 17.0.3

**Comment by alex-dani** [comment]
any updates or workarounds here? @MrLepage did you find a solution for this?

**Comment by Tkko** [comment]
You can use the `Pinput.builder` and implement a custom pins where you show the cursor anytime you want.
