### ISSUE TITLE
postFilledWidget parameter feature

### ISSUE THREAD

**Issue by mg3994** [Tkko/Flutter_Pinput#153]
**Is your feature request related to a problem? Please describe.**
I was Trying to add a small Grey Colored bar at bottom like =>
```dart
Column( //like preFilledWidget
      mainAxisAlignment: MainAxisAlignment.end,
      children: [
        Container(
          width: 56,
          height: 3,
          decoration: BoxDecoration(
            color: Colors.grey[100],
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ],
    )
```

 with the help of submittedPinTheme but , but i doesn't found any method to do so 

**Describe the solution you'd like**
Add a Extra Parameter for postFilledWidget , so that we can align a bar at bottom even after submitted Pin Field / ...many more

**Describe alternatives you've considered**
or else you can change the Data type of BoxDecoration? decoration, in PinTheme 

**Additional context**
None

**Comment by Tkko** [comment]
Hi, I'm trying to avoid adding new properties since people are already overwhelmed. You can use the `Pinput.builder` to implement the individual pins however you want.
