### ISSUE TITLE
External state management

### ISSUE THREAD

**Issue by Hithori** [Tkko/Flutter_Pinput#155]
**Is your feature request related to a problem? Please describe.**
Working with custom pinpad (not a native keyboard), I can't directly influence the state of the pinput.

**Describe the solution you'd like**
Maybe field that represents current pinput state so that it can be changed by an external state manager.

**Additional content**
Maybe I can manage state without it but I haven't found anything suitable.

**Comment by Tkko** [comment]
Hey @Hithori, You should set the `controller` and `useNativeKeyboard` properties and call `controller.append` when user types on your custom keyboard

**Comment by Hithori** [comment]
> Hey @Hithori, You should set the `controller` and `useNativeKeyboard` properties and call `controller.append` when user types on your custom keyboard

But how to call onSubmit callback?

**Comment by Tkko** [comment]
onCompleted callback will be called once the user enters the entire code

**Comment by Hithori** [comment]
submittedPinTheme isn't called if the field is completely filled

**Comment by Hithori** [comment]
or defaultPinTheme isn't working I don't understand
```dart
              Pinput(
                controller: controller,
                obscureText: true,
                length: 4,
                useNativeKeyboard: false,
                separatorBuilder: (index) => const Gap(16),
                cursor: const SizedBox.shrink(),
                hapticFeedbackType: HapticFeedbackType.heavyImpact,
                pinAnimationType: PinAnimationType.fade,
                onChanged: (value) => context.read<InputPinBloc>().add(
                      InputPinEvent.input(input: value),
                    ),
                obscuringWidget: SizedBox.shrink(),
                errorPinTheme: defaultPinTheme(
                  context,
                  color: AppColors.supportColorsRed,
                ),
                submittedPinTheme: defaultPinTheme(
                  context,
                  color: AppColors.brandColorGreen,
                ),
                pinputAutovalidateMode: PinputAutovalidateMode.onSubmit,
                inputFormatters: [
                  FilteringTextInputFormatter.digitsOnly,
                ],
                defaultPinTheme: defaultPinTheme(
                  context,
                  color: AppColors.background3,
                ),
              ),
```
where
```dart
PinTheme defaultPinTheme(
    BuildContext context, {
    Color color = AppColors.background3,
  }) =>
      PinTheme(
        height: context.wh(12),
        width: context.wh(12),
        decoration: BoxDecoration(
          color: color,
          shape: BoxShape.circle,
        ),
      );
```

**Comment by Tkko** [comment]
I'm actually planning to remove predefined theme properties and add builder method like Material components have, because the API is kinda bloated 🙈.

Is it possible to share the UI that you are building? I'll let you know if you will be able to do it in the current Pinput version

**Comment by Hithori** [comment]
@Tkko 
I'm covering by `obscuringWidget` pin elements and change `obscuringWidget`'s state, so I'm able to make what I need
```
                  obscuringWidget: Container(
                    height: context.wh(12),
                    width: context.wh(12),
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: state.map(
                        firstPin: (value) => AppColors.brandColorGreen,
                        secondPin: (value) => AppColors.supportColorsGreen,
                      ),
                    ),
                  ),
```
