### ISSUE TITLE
Permissions  are not remembered in pinput every time system fetch otp it asks user to allow promt for auto fill how can we tackle that ? is there any solution

### ISSUE THREAD

**Issue by FontierCorps** [Tkko/Flutter_Pinput#158]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Pinput version:** [e.g. 1.0.0]

**Result of:** `flutter doctor --verbose`
<details>
[!] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en)
    • Flutter version 3.10.0 on channel stable at /Users/dev/fvm/versions/stable
...
</details>

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tkko** [comment]
I recommend to enable the [SMS retriever APi](https://github.com/Tkko/Flutter_Pinput#sms-retriever-api) it will read the SMS automatically.
