### ISSUE TITLE
AutoFill not appearing second time on requesting resend OTP

### ISSUE THREAD

**Issue by DhineshJ** [Tkko/Flutter_Pinput#160]
**Describe the bug**
 Assume that I have a text field.
1. On first OTP request , it will show the consent to allow or deny the read permission. 
2. Assume that I'm denying the first request.
3. From second attempt, the consent screen was not appearing. 
4. My query is whether consent screen not appearing due to that denial ?

**Comment by rishabh2000jain** [comment]
Hi @DhineshJ 
you can pass listenForMultipleSmsOnAndroid as true in Pinput widget.
