### ISSUE TITLE
On Android API 34 (Android 14) sms retriever not working - Update smart_auth dependency

### ISSUE THREAD

**Issue by DaanVanRuijvenTide** [Tkko/Flutter_Pinput#166]
**Describe the bug**
On Android 14 Flutter_Pinput will throw an exception when trying to autofill sms codes. This is due to a change in the Android API requesting a change in the implementation. The `smart_auth` package has released an update on 21/01/2024 to resolve this.

See the PR that resolved it https://github.com/Tkko/flutter_smart_auth/pull/16 and the issue raised for it https://github.com/Tkko/flutter_smart_auth/issues/15

**Pinput version:** 3.0.1

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Android API 34+

**Comment by elbozordev** [comment]
Has any news about this bug?

**Comment by DaanVanRuijvenTide** [comment]
@elbozordev if you can't wait for this package to be updated you can use your own fork with changes similar to the one I've created myself: https://github.com/DaanVanRuijvenTide/Flutter_Pinput

There's also a PR open on this repo that fixes the same, however it doesn't resolve the example app which should have gradle values updated. See the PR just above your comment.
