### ISSUE TITLE
Unresolved reference: AppSignatureHelper

### ISSUE THREAD

**Issue by miguelmobilat** [Tkko/Flutter_Pinput#168]
smart_auth-2.0.0/android/src/main/kotlin/fman/ge/smart_auth/SmartAuthPlugin.kt:99:26 Unresolved reference: AppSignatureHelper
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smart_auth:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

 - Version 4.0.0

**Comment by iquirino** [comment]
+1 Solved with a rollback version

**Comment by alaincruz06** [comment]
@iquirino which version did you rollback-ed into? I´m trying with smart_auth: ^1.1.1 (the previous, since the latest is smart_auth: ^2.0.0) and getting the same bug.

**Comment by JesusHdez960717** [comment]
@miguelmobilat @iquirino @alaincruz06 my team and I were struggling with the same problem, and the solution we came to, was using Kotlin version 1.8.0 (same as the `smarth_auth: 2.0.0`)

According to docs:

> We should set project kotlin version to 1.8.0 or above because of the new requirement for sdk 34 RECEIVER_EXPORTED. Or we would get duplicate class error in different kotlin versions.
> 
> so in the android level build.gradle file update the kotlin version like below:
> 
> // android/build.gradle`
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.8.0'
> }
> ```

So bassically we end using `pinput: 4.0.0` (that under the hood uses `smart_auth: 2.0.0`) and `kotlin_version = '1.8.0'`

BTW, the `above` was purely a suggestion :sweat_smile:, we were using `kotlin_version  = '1.9.0'` and it doesn't work

Feel free to test this (i don't know why it works) solution and give us feedback if it works for you too

**Comment by deepss1** [comment]
> @miguelmobilat @iquirino @alaincruz06 my team and I were struggling with the same problem, and the solution we came to, was using Kotlin version 1.8.0 (same as the `smarth_auth: 2.0.0`)
> 
> According to docs:
> 
> > We should set project kotlin version to 1.8.0 or above because of the new requirement for sdk 34 RECEIVER_EXPORTED. Or we would get duplicate class error in different kotlin versions.
> > so in the android level build.gradle file update the kotlin version like below:
> > // android/build.gradle`
> > ```
> > buildscript {
> >     ext.kotlin_version = '1.8.0'
> > }
> > ```
> 
> So bassically we end using `pinput: 4.0.0` (that under the hood uses `smart_auth: 2.0.0`) and `kotlin_version = '1.8.0'`
> 
> BTW, the `above` was purely a suggestion 😅, we were using `kotlin_version = '1.9.0'` and it doesn't work
> 
> Feel free to test this (i don't know why it works) solution and give us feedback if it works for you too

This worked, feels illegal but yes 😅 

I had to change the kotlin version from `1.8.22` to `1.8.0`

This might mean that the kotlin version in `smart_auth` needs to be upgraded 🤔

**Comment by Tkko** [comment]
SmartAuth was removed from Pinput in versions ^5.0.0, so that I don't force people who don't want to use SMS autofill to depend on it and avoid building issue like this.

If you need the SMS autofill on android and still having same issue, please checkout the [SmartAuth](https://github.com/Tkko/flutter_smart_auth) repo.
