### ISSUE TITLE
Is it possible to replicate following layout?

### ISSUE THREAD

**Issue by rodrigobastosv** [Tkko/Flutter_Pinput#175]
Thanks very much for the great package.

I could not find ways to replicate the following design for the focusedPin:

<img width="88" alt="Screenshot 2024-03-23 at 08 52 09" src="https://github.com/Tkko/Flutter_Pinput/assets/12686272/7b9fd9e7-2a2c-4e48-949d-4a7a13ba6583">

It's very easy to replicate the inner border, but i could not find a way to replicate the both inner and outer borders.

**Comment by Tkko** [comment]
Each pin is basically a DecoratedBox so you can build anything that could be built with Container. But I don't think you can have both inner and outer border at the same time.

I'll add custom build constructor in future to make the pins more customisable.

**Comment by Tkko** [comment]
Additionally, the `Pinput.builder` constructor is available so you can implement your custom layout.
