### ISSUE TITLE
Doesn't work on PWA WEB

### ISSUE THREAD

**Issue by rhomayouni** [Tkko/Flutter_Pinput#181]
Hello, the pinput library works on android correctly, but it doesn't work on mobile browser(it doesn't read opt from sms and fill the field), please help me.

**Comment by Tkko** [comment]
Hi, what exactly isn't working?

**Comment by rhomayouni** [comment]
In pwa mode on the mobile phone (android) when the OTP is received by SMS, the received code is not placed in the box.

**Comment by Tkko** [comment]
That's an expected behavior. The SMS retriever API only works in compiled Android app.

**Comment by rhomayouni** [comment]
i checked in 2 modes: smsUserConsentApi, smsRetrieverApi , noth of them are same.

**Comment by rhomayouni** [comment]
so in pub.dev, you told support WEB

**Comment by Tkko** [comment]
Sorry, forgot to mention, none of these APIs are working on the Web. If you send supposed SMS format the code will pop up on the keyboard.

The supported SMS formats aren't clear, but it seems to work in English most of the time.
For example:

_Code 466345_

**Comment by rhomayouni** [comment]
thanks man, Even the received code is not placed at the top of the keyboard.

**Comment by Tkko** [comment]
Hmm, Just checked and it's not working on Android Web. But it has to be working out of the box with TextField if you pass 
`autofillHints: [AutofillHints.oneTimeCode],`

https://api.flutter.dev/flutter/material/TextField/autofillHints.html
https://api.flutter.dev/flutter/services/AutofillHints/oneTimeCode-constant.html

**Comment by Tkko** [comment]
Since there has been no response or follow-up, I am closing this issue for now. If you still encounter the problem or need further assistance, feel free to reopen the issue or create a new one. Thank you!
