### ISSUE TITLE
Text widget appearing in case of error

### ISSUE THREAD

**Issue by celikdemirrberkay** [Tkko/Flutter_Pinput#183]
I only want to make the boxes around the pinput red in case of error. However, when there is an error, a text appears under the pinput and spoils my design. It appears whether I send the text empty or null. Can you prevent the text from appearing in the new version? Thank you so much

**Comment by Tkko** [comment]
Hi @celikdemirrberkay, You can use the `errorBuilder` property and return SizedBox.shrink() as a error widget.
