### ISSUE TITLE
Is there any property to set the otp text direction from left to right or right to left? Because if the language is Arabic, its direction changes from left to right to right to left.

### ISSUE THREAD

**Issue by muhammadahmad-15** [Tkko/Flutter_Pinput#187]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tkko** [comment]
Hi, when you set the `locale` in `MaterialApp` the text direction will work as expected

```dart
    MaterialApp(
      localizationsDelegates: const [
        GlobalCupertinoLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('fa', 'IR'),
      ],
      locale: const Locale('fa', 'IR'),
      home:  MyApp(),
  )
```

**Comment by muhammadahmad-15** [comment]
I'm using multiple languages so it was only thing that i needed to adjust.
I just wrapped Pininput widget with Directionality widget and set its direction to TextDirection.ltr and it worked.
Thanks for responding!!
