### ISSUE TITLE
Paste button isn't shown on mobile web

### ISSUE THREAD

**Issue by agordeev** [Tkko/Flutter_Pinput#188]
Tested on example app.

On iOS, the long press shows the paste button.

On web iOS, the long press does nothing.

iOS app (works as expected):

https://github.com/Tkko/Flutter_Pinput/assets/2883524/e266e8c3-2e32-400a-82b5-1c98372baf5e

iOS web app (doesn't work as expected):

https://github.com/Tkko/Flutter_Pinput/assets/2883524/9a12c690-b6fc-4745-bd4e-cd2c7a9d708e

**Comment by Tkko** [comment]
Hi @agordeev, Sorry for the late reply, on the web you have to disable the default context menu

```dart
  @override
  void initState() {
    super.initState();
    BrowserContextMenu.disableContextMenu();
  }

  @override
  void dispose() {
    BrowserContextMenu.enableContextMenu();
    super.dispose();
  }
```

**Comment by Evgenia-bit** [comment]
Flutter-rendered paste button does not work ((

https://github.com/user-attachments/assets/e3bd5a3b-a893-460b-80d0-a44bf1894d68
