### ISSUE TITLE
Throw an error if clipboard is empty

### ISSUE THREAD

**Issue by ortaras** [Tkko/Flutter_PinPut#19]
[Unhandled](url) Exception: NoSuchMethodError: The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty[](url)

pin_put_bloc.dart -> line 55 -> return _clp.isNotEmpty;

_clp is null

Steps to reproduce: 
1) Errase all content on the device
<img width="696" alt="Screen Shot 2019-06-14 at 12 26 04 AM" src="https://user-images.githubusercontent.com/11505514/59468542-03d4c080-8e3b-11e9-9922-9800af37688b.png">

2) Open the page with PinPut widget
<img width="696" alt="Screen Shot 2019-06-14 at 12 24 39 AM" src="https://user-images.githubusercontent.com/11505514/59468477-cff99b00-8e3a-11e9-9e13-157b1749c654.png">

**Comment by Tkko** [comment]
Fixed.
