### ISSUE TITLE
Ability to remove autofill

### ISSUE THREAD

**Issue by Yagorundy** [Tkko/Flutter_Pinput#190]
**Is your feature request related to a problem? Please describe.**

Hi! I am trying to remove the autofill for web desktop versions.
Having `AutofillHits.oneTimeCode` prompts desktop web browsers to autofill user passwords in the pin code field.

When using `Pinput()` constructor, best I can do is provide empty array `[]` to `autofillHints`, since if I provide null the value is resolved to:
    this.autofillHints = const [
      AutofillHints.oneTimeCode,
    ],
When I provide empty array, there is still autofill configuration created for the input. For desktop web browsers it still hints user passwords for the pin field.

https://github.com/user-attachments/assets/3684ed64-d4c3-4e29-be84-318fa3618105

Only way to disable the autofill configuration is to provide `null` to this property, and only way to do that is to use `Pinput.builder()`
However, I want to use the widgets provided by you package, and `Pinput.builder()` forces me to provide a `builder`.

**Describe the solution you'd like**
I think the easiest solution would be to make `builder` in `Pinput.builder()` nullable. This way I can pass `null` to `autofillHints` to remove the autofill (since there isn't a default value in the `Pinput.builder()` constructor) and I could also pass `null` to `builder` so I can use the package provided widgets.

@Tkko

**Comment by Tkko** [comment]
Hi @Yagorundy, if you provide null the `autofillHints` should be resolved as null instead of the default value.
| null | array |
|---|---|
| ![Screenshot 2024-08-19 at 1 01 55 PM](https://github.com/user-attachments/assets/a8739113-fb2a-48ee-9715-ef016f6bd342) | ![Screenshot 2024-08-19 at 1 02 39 PM](https://github.com/user-attachments/assets/3d2ee2ac-0280-4789-a24d-2933044d73e5) |

**Comment by Yagorundy** [comment]
@Tkko 
All is good, providing `null` to `autofillHints` works. Thanks!
