### ISSUE TITLE
Show error msg without losing keyboard focus

### ISSUE THREAD

**Issue by Princewil** [Tkko/Flutter_Pinput#191]
First, thanks for this wonderful package. 

Currently, the validator works only when the pin is completed, which is fine. However this makes the keyboard to loose its focus prompting user to tap before focus is regained for correction. Is it possible to validate the pin after it's completed without losing keyboard focus inorder to enable faster user's interaction.

I am running app on desktop by the way.

**Comment by Tkko** [comment]
Hi @Princewil, you can set the `closeKeyboardWhenCompleted` property to false.
