### ISSUE TITLE
Adding multiple decoration for each code

### ISSUE THREAD

**Issue by hapk-inc** [Tkko/Flutter_Pinput#193]
Implement different decorations for each word in a text field.

This feature can help us identify when some characters in the code entered by the user are partially correct. I can highlight these characters to indicate which parts are correct and prompt the user to fill in the remaining blanks.

Please let me know if there are any alternatives. If not, are there any plans to work on this request?

**Comment by Tkko** [comment]
You can use `Pinput.builder` constructor to implement this kind of custom behavior.
