### ISSUE TITLE
Bug: SmartAuth getSmsCode is not supported on TargetPlatform.iOS

### ISSUE THREAD

**Issue by burekas7** [Tkko/Flutter_Pinput#194]
Hi,

I use your `SmsRetrieverImpl` implementation.
There is a bug regarding the `getSmsCode()`.

```
  @override
  Future<String?> getSmsCode() async {
    final res = await smartAuth.getSmsCode();
    if (res.succeed && res.codeFound) {
      return res.code!;
    }
    return null;
  }
```

It's ok when running Android.

But when running iOS, there is an error:
`flutter: SmartAuth getSmsCode is not supported on TargetPlatform.iOS`

So I add this condition: `Platform.isAndroid`, but on iOS the screen is getting stuck, I can't press on anything.
Maybe it shouldn't be `return null`? (I tried also `return ''`, doesn't work)

```
  @override
  Future<String?> getSmsCode() async {
    if (Platform.isAndroid) {
      final res = await smartAuth.getSmsCode();
      if (res.succeed && res.codeFound) {
        return res.code!;
      }
    }
    return null;
  }
```

**Pinput version: 5.0.0**

Flutter: 3.24.2
iOS: 17.5.1

**Comment by burekas7** [comment]
This is the solution:
```
Pinput(
      smsRetriever: Platform.isAndroid ? smsRetrieverImpl : null,
```

**Comment by burekas7** [comment]
@Tkko 
Is this the correct way to solve it?
I know that previously for iOS the code was shown above the keyboard.

**Comment by Tkko** [comment]
Hi @burekas7, on iOS the SMS autofill (the code is showing above the keyboard) is working out of the box without additional implementation and the `SmartAuth` only supports Android, so yes the solution is correct.
