### ISSUE TITLE
Alternatives to listenForMultipleSmsOnAndroid and OTP Autofill Issues in Latest Android Version

### ISSUE THREAD

**Issue by FuadAghjayev** [Tkko/Flutter_Pinput#195]
In the latest version, the listenForMultipleSmsOnAndroid feature has been removed. What can I use instead? The autofill feature doesn't work when the OTP arrives for the second time.

Pinput version: 5.0.0

**Comment by Tkko** [comment]
https://github.com/Tkko/Flutter_Pinput/blob/master/MIGRATION.md
