### ISSUE TITLE
How to make the number field underlined and add some text at the top?

### ISSUE THREAD

**Issue by annagat** [Tkko/Flutter_PinPut#23]
Hi!

A newbie here. I can't find how to set the number field underlined not boxed. Also can I put some text at the top, ex, "Please enter pin code".

Thanks.

**Comment by Tkko** [comment]
@annagat For underline text you can set text style
```
             textStyle: TextStyle(
                   decoration: TextDecoration.underline,
                ),
```
helper text isn't currently implemented

**Comment by annagat** [comment]
Thank you.
