### ISSUE TITLE
How to get the value if the user just edit the value in some digits without going onsubmit ?

### ISSUE THREAD

**Issue by Goodest-Y** [Tkko/Flutter_PinPut#24]
HI all,

first the package is awesome , yet I have a question about how to get the pin if the user in case he didn't go through all digits to trigger onsubmit fucntion ?

thanks.

**Comment by MohammedAkhil** [comment]
@Goodest-Y have you found the solution to this? Even I need to get the pin before pressing the onsubmit funcrion

**Comment by Tkko** [comment]
In version 0.1.10+  it is possible with the help of TextEditingController.
