### ISSUE TITLE
Clear button isnt working and is giving an error

### ISSUE THREAD

**Issue by Kinnear** [Tkko/Flutter_PinPut#27]
Ever since the later versions of flutter the clear button gives us an error. 
![error](https://user-images.githubusercontent.com/7753323/75604078-003fb180-5b10-11ea-8a81-3167513c08ea.PNG)

**Comment by KimKiHyuk** [comment]
because you didn't pass String parameter.

Passing onClear(function) to PinPut() with String.

and then, clear button would work well

```
child: Center(
                      child: PinPut(
                        onClear: (String pin){
                          print('pin back button has been clicked');
                        },
                        fieldsCount: 4,
....
```

**Comment by Tkko** [comment]
> because you didn't pass String parameter.
> 
> Passing onClear(function) to PinPut() with String.
> 
> and then, clear button would work well
> 
> ```
> child: Center(
>                       child: PinPut(
>                         onClear: (String pin){
>                           print('pin back button has been clicked');
>                         },
>                         fieldsCount: 4,
> ....
> ```

Agreed.
