### ISSUE TITLE
No way to cancel operation

### ISSUE THREAD

**Issue by lcrocker** [Tkko/Flutter_PinPut#3]
Works fine when allowed to complete. But I have a button on my page "Continue without PIN", which allows the user to continue using the app, just with limited access to some features. When I use this, the PinPut's current FocusNode retains focus, and so the keyboard is left up for my next screen, interfering with it. I've tried the "FocusScope.of(context).requestFocus(FocusNode())" trick to dismiss the keyboard, but it doesn't work. I need some way to call unfocus() on the currently focused TextField before moving on to my next screen.

**Comment by Tkko** [comment]
Got it, Added unFocusWhen property, it will be available soon.
