### ISSUE TITLE
Tapping on the textfield don't open (virtual) keyboard

### ISSUE THREAD

**Issue by imarindam** [Tkko/Flutter_PinPut#30]
Hello there,
Hope you are doing fine. 
I want to inform you about just one last issue. When keyboard isn't visible, if I tap on the textfields exactly, it does not open the keyboard. However, If I tap on the black space in between the text fields, the keyboard shows up.
My code for PinPut is as follows:
`PinPut(
              fieldsCount: 6,
              autofocus: false,
              onSubmit: (otp) {
                if (otp.length == 6) _submitOTP(otp);
                print('otp submitted');
              },
              eachFieldPadding: EdgeInsets.all(5),
              focusNode: _otpFocusNode,
              controller: _otpController,
              onClipboardFound: (value) => _otpController.text = value,
              pinAnimationType: PinAnimationType.fade,
              textStyle: TextStyle(
                fontSize: 20,
                color: Colors.white,
                fontWeight: FontWeight.w800,
              ),
              selectedFieldDecoration: _pinPutDecoration,
              submittedFieldDecoration: _pinPutDecoration.copyWith(
                  color: appMainColorLight,
                  border: Border.all(color: appMainColorLight)),
              followingFieldDecoration: _pinPutDecoration.copyWith(
                  color: Colors.white, border: Border.all(color: Colors.white)),
            )`

I am attaching a screenshot for your reference.
Thank you for your time and support.
![screencast-Genymotion-2020-04-16_13 42 38 037](https://user-images.githubusercontent.com/18639540/79431955-c73c9d00-7fe8-11ea-8a75-0d0f4460a867.gif)

**Comment by Tkko** [comment]
Hello, Thanks for this issue.
it should work correctly in version 0.2.3.

**Comment by imarindam** [comment]
Sir,
I am using the latest version 0.2.3.

**Comment by Tkko** [comment]
That's weird I have tested it on both android and Ios.
Would you please check it on real device?

**Comment by imarindam** [comment]
I have tested it on Redmi Note 8 pro. Same problem happening.
If you want I can share screenshot with you.

**Comment by Tkko** [comment]
@imarindam Discord channel for faster communication.
https://discord.gg/ssE8eh

**Comment by imarindam** [comment]
@Tkko Thank you so much for your time and support.
This problem is fixed when I switched back to flutter stable channel as you have pointed out.
So the issue was due to beta channel.

Thank you once again. Everything is working fine now.

**Comment by Tkko** [comment]
Great.
