### ISSUE TITLE
RTL not needed

### ISSUE THREAD

**Issue by TG-Ketan-Patel** [Tkko/Flutter_Pinput#31]
The application is in Hebrew having HE culture set. This normal text input is expected to be of RTL. But for PIN it should remain LTR as this will be numbers only. Can you suggest how to do so?

**Comment by Tkko** [comment]
I'll add that feature in the next release.

**Comment by Tkko** [comment]
Done, Version 2.1.0.
Reopen if needed.

**Comment by SnirYaZem** [comment]
I'm having the same problem. How can I enforce LTR while application is RTL?

I tried wrapping Pinput widget in a directionality widget with TextDirection.ltr but then the error message is LTR instead of RTL.
