### ISSUE TITLE
Set PinPut value programmatically

### ISSUE THREAD

**Issue by sinuraya** [Tkko/Flutter_PinPut#33]
So many changes since last time I'm using this awesome package. Bravo and good job to the developers. 
Right now, I have a case like this. a user wants to fill up the pin put field automatically when authentication sms received. Let say I can retrieve the auth code programmatically and  then want to set the code as pinput value and show it to user. How can I do that?

**Comment by Tkko** [comment]
1) Initialize controller
`final TextEditingController _pinPutController = TextEditingController();`
2) Set `controller: _pinPutController`
3) Set controller text `_controller.text = '1234'`

**Comment by sinuraya** [comment]
Thank you for quick reply, I will check it out.

**Comment by sinuraya** [comment]
I already tried it. It worked until you have to delete the text using backspace.

**Comment by sinuraya** [comment]
the error is: Text selection index was clamped (-1->0) to remain in bounds. This may not be your fault, as some keyboards may select outside of bounds.

**Comment by sinuraya** [comment]
I found a workaround. Don't finalize the TextEditingController, make it dynamic. 

Set `controller = TextEditingController(text: newValue)`

**Comment by sinuraya** [comment]
My bad, that didn't work either.

**Comment by sinuraya** [comment]
I wonder if you can add set pin method or just expose each field texteditingcontrol

**Comment by Tkko** [comment]
> edi

Hmm I don't think it's needed.
Tell me how to reproduce error i'll take a loot at it.

**Comment by sinuraya** [comment]
I just look into your code and there is nothing wrong about it. You set a transparent textedit, extract characters from it and then display in fields. It worked in normal use case. 

What I want to achieve is display pin input and display a remaining time to get new pin from server. 
here is the snippet:
  
` int _countDown = 100;
  Timer _timer;
  final FocusNode _pinFocusNode = FocusNode();
  final TextEditingController _pinController = TextEditingController();

  void startTimer() {
    if (_timer != null) {
      _timer.cancel();
    }
   _timer = Timer.periodic(Duration(seconds: 1), (timer) { 
      if (_counter <= 1) {
        _timer.cancel();
      }
      setState({
        _countDown--;
      });
    });
}

void initState() {
  startTimer();
}
`
void dispose() {
  _timer.cancel();   
}

Widget build(BuildContext context) {
  _pinController.text = _countDown.toString().padLeft(4, "0");
  return Column(
    children: <Widget>[
        PinPut (
                textStyle: TextStyle(
                  fontSize: 18.0
                ),
                fieldsCount: 4,
                preFilledChar: "-",                  
                onSubmit: (String pin) {
                  print(pin);
                  _currentText = pin;
                },                  
                focusNode: _pinFocusNode,
                controller: _pinController,                
              ),,
        TextI("Count down : $_countDown")
     ],
  );
}
`
