### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by hoponaillc** [Tkko/Flutter_PinPut#35]
I am using GlobalKey based form validation. Validation always returning true. 

  PinPut(
                      fieldsCount: 6,
                      autoValidate: false,
                      autofocus: true,
                      onSubmit: (String pin) async{

                         print('pin is' + pin);                       

                      },
                      //focusNode: _pinPutFocusNode,
                      controller: _pinPutController,
                      submittedFieldDecoration: _pinPutDecoration.copyWith(
                        borderRadius: BorderRadius.circular(20)),
                      selectedFieldDecoration: _pinPutDecoration,
                      followingFieldDecoration: _pinPutDecoration.copyWith(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(
                          color: Colors.black,
                        ),
                      ),
                    ),

===========

  onPressed: () async {
                       if (**_formKey.currentState.validate())** {                            
                              print('pin is');
                               int score = await Future.delayed(
                              const Duration(milliseconds: 4000), () => 42);
                            setState(() {
                              //_pageState = 2;
                            }); 
                         
                        }
                      },
                    ),

**Comment by Tkko** [comment]
Hello @hoponaillc  You  need to set `validator` property like so.
```
          validator: (s) {
            if (s.contains('1')) return null;
            return 'NOT VALID';
          },
```
