### ISSUE TITLE
Need way to unfocus TextFields

### ISSUE THREAD

**Issue by lcrocker** [Tkko/Flutter_PinPut#4]
My app has a button "Continue without PIN", which allows the user to continue using the app but with limited access. When this button is pressed, I move on to the next page, but the keyboard is still up and in the way. I've tried the "FocusScope.of(context).requestFocus(FocusNode())" trick, but that doesn't work. I need a way to unfocus the currently focused node before navigating off the page.

**Comment by Tkko** [comment]
Got it.
