### ISSUE TITLE
onChanged method execute Twice when pipput text is change

### ISSUE THREAD

**Issue by masoudpaidar** [Tkko/Flutter_PinPut#40]
my package version is pinput: ^0.2.6 

when the pinput text was change the onchange method execute twice like this implementation print the text in two time

Widget darkRoundedPinPut() {
    final BoxDecoration pinPutDecoration = BoxDecoration(
      color:  Colors.red,
      borderRadius: BorderRadius.circular(20.0),
    );
    return PinPut(
      onChanged: (text){
        print(text);
      },
      eachFieldWidth: 65.0,
      eachFieldHeight: 65.0,
      fieldsCount: 4,
      focusNode: _pinPutFocusNode,
      controller: _pinPutController,
      onSubmit: (String pin) => _showSnackBar(pin),
      submittedFieldDecoration: pinPutDecoration,
      selectedFieldDecoration: pinPutDecoration,
      followingFieldDecoration: pinPutDecoration,
      pinAnimationType: PinAnimationType.scale,
      textStyle: const TextStyle(color: Colors.white, fontSize: 20.0),
    );
  }

my flutter doctor result:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-8.0.pre.356, on Microsoft Windows [Version
    10.0.18363.1198], locale fa-IR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

**Comment by liri2006** [comment]
Had same issue and in my case the reason was that right after I've got submit callback I was doing _controller.clear(); which resulted in one more submit callback execution.
Resolved by calling clear() in addPostFrameCallback.
