### ISSUE TITLE
can't run example

### ISSUE THREAD

**Issue by sgehrman** [Tkko/Flutter_PinPut#43]
Running "flutter pub get" in example...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Launching lib/main.dart on HD1905 in debug mode...
lib/main.dart:1

FAILURE: Build failed with an exception.

* Where:
Build file '/home/steve/google/Flutter_PinPut/example/android/build.gradle'

* What went wrong:
Could not compile build file '/home/steve/google/Flutter_PinPut/example/android/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57

  java.lang.IllegalArgumentException: Unsupported class file major version 57
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)

**Comment by Tkko** [comment]
Thanks for the issue, Fixed.
