### ISSUE TITLE
border shows when unfocused

### ISSUE THREAD

**Issue by sgehrman** [Tkko/Flutter_Pinput#45]
Widget get _hiddenTextField 

 You need to turn off all the borders

      border: InputBorder.none,
      disabledBorder: InputBorder.none,
      enabledBorder: InputBorder.none,
      focusedBorder: InputBorder.none,
      errorBorder: InputBorder.none,
      focusedErrorBorder: InputBorder.none,

**Comment by Tkko** [comment]
Sorry for late response,
Fixed, Just uploaded new refactored version 2.0.0. Thank you!
