### ISSUE TITLE
Vulnerable to Intent Redirection

### ISSUE THREAD

**Issue by karatasemre** [Tkko/Flutter_PinPut#48]
Hi,

When I use the PinPut package, when I send the application to the market, I get a warning like the following and my application is reject.

"Your app(s) are vulnerable to Intent Redirection."

I think he listens to sms because of his onClipboardFound feature and this causes a security vulnerability. Is there a situation you can suggest or a setting where I can turn this off? What should I do about it?

**Comment by Tkko** [comment]
Added property `checkClipboard`

**Comment by SamuelMTDavies** [comment]
@Tkko Has this been removed?

i am also facing this issue and I am unsure if it's to do with app signatures or the clipboard functionality.

The checkClipboard has been removed and onClipboardFound seems to be the closest property I can find int he current version

**Comment by Tkko** [comment]
@SamuelMTDavies  If `onClipboardFound` is null the widget won't try to read the `ClipBoardData`. The `checkClipboard` was removed because it was doing the same thing.
