### ISSUE TITLE
Unexpected container behind the PinPut fields

### ISSUE THREAD

**Issue by matszafraniec** [Tkko/Flutter_PinPut#49]
Hello,

please take a look on screenshot below:
![Simulator Screen Shot - iPhone 11 - 2021-02-04 at 13 17 49](https://user-images.githubusercontent.com/31272038/106891935-a8c89f00-66eb-11eb-9123-d785dd2075f7.png)

I don't get why there is this rounded container behind the PinPut fields? I'm using the latest version of package.

Here is my code:
```dart
import 'package:flutter/material.dart';
import 'package:pinput/pin_put/pin_put.dart';

class PinputPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Pinput page',
        ),
      ),
      body: Center(child: _buildPinput()),
    );
  }

  Widget _buildPinput() {
    BoxDecoration defaultDecor = BoxDecoration(
      color: Colors.white,
      borderRadius: BorderRadius.circular(25),
      border: Border.all(
        color: Colors.blue,
        width: .2,
      ),
    );

    return PinPut(
        fieldsAlignment: MainAxisAlignment.center,
        eachFieldWidth: 45,
        eachFieldHeight: 45,
        fieldsCount: 4,
        submittedFieldDecoration: defaultDecor.copyWith(
          color: Colors.grey[300],
        ),
        selectedFieldDecoration: defaultDecor.copyWith(
            border: Border.all(
          color: Colors.blue,
          width: .6,
        )),
        followingFieldDecoration: defaultDecor,
        pinAnimationType: PinAnimationType.scale,
        textStyle: const TextStyle(
          color: Colors.blue,
          fontSize: 16,
        ),
        onSubmit: (value) => print('onSubmit $value'));
  }
}
```

**Comment by matszafraniec** [comment]
Ok. The issue was that I have predefined `inputDecoration` in app themes :)

**Comment by 70nybl4nc0** [comment]
How to fix this issue?

**Comment by matszafraniec** [comment]
> How to fix this issue? In my case, i need to define the `ThemeData.inputDecoration`, and i can't see how to use the hideInputDecoration used in the package.
> 
> EDIT:
> 
> I see, flutter is filling the `hideInputDecoration` with defaults from the Theme.

On my side I had `inputDecorationTheme` set in ThemeData with `fillColor: Colors.white`. That's why I had white color as a background behind pin puts.
