### ISSUE TITLE
Custom Numpad

### ISSUE THREAD

**Issue by PenCone** [Tkko/Flutter_PinPut#50]
Hi, is it possible to disable the devices keyboard, just like with the usual 'readOnly' setting for text fields, and use a custom numpad for input? 
The iOS and Android numpads aren't suitable for my app.

**Comment by ThierryDD** [comment]
This issue has been mentioned on StackOverflow: https://stackoverflow.com/questions/66551419

This is how it was worked around:

## How to hide the Keyboard... while keeping the focus blinking cursor

### 1. disable the focus on your PinPut fields:

For this, we used a class described [here](https://stackoverflow.com/questions/55234039)...

```dart
class AlwaysDisabledFocusNode extends FocusNode {
  @override
  bool get hasFocus => false;
}
```

...as the `focusNode` of the `PinPut`:

```dart
class PinInput extends StatelessWidget {
  [...]
  @override
  Widget build(BuildContext context) {
    final size = 60.0;
    final FocusNode _pinPutFocusNode = AlwaysDisabledFocusNode();
    // _pinPutFocusNode.unfocus();

    return PinPut(
      [...]
      focusNode: _pinPutFocusNode,
      [...]
    );
  }
}
```

So, now, the `PinPut` never gets the focus. The Soft Keyboard is not shown but, hey!, we lost the blinking cursor!

No worries, we'll keep it always on programmatically.

## 2. Keep the blinking cursor always on

For this, though, we'll have to change the code of the [pinput package][1].

Currently, in `PinPutState`, the blinking cursor is shown on the next field if `withCursor` is set to `true`  and the `PinPut` has the focus. Instead, we will always show the blinking cursor if `withCursor`is set to `true`:

```dart
if (widget.withCursor /* && _focusNode!.hasFocus */ && index == pin.length) {
  return _buildCursor();
}
```

**Comment by Tkko** [comment]
Thanks you all. I have added `useNativeKeyboard` property and some examples
