### ISSUE TITLE
pin length goes beyond field count. (linux)

### ISSUE THREAD

**Issue by maltortan** [Tkko/Flutter_Pinput#55]
The same thing that works on android is showing an error on Linux. even though the field count is being shown normal the length of strings goes beyond fields count.
![image](https://user-images.githubusercontent.com/16833813/121513153-3e619b80-ca0a-11eb-8f7e-d33b0590e4e7.png)

**Comment by Smithtekk** [comment]
I'm getting the same issue @Tkko @maltortan.

The TextEditingController appears to allow you to go past the fieldsCount parameter. I have a workaround by using onChanged but it is very slow. 

Any update as to a fix here?

**Comment by Tkko** [comment]
Sorry for late response,
Just uploaded new refactored version 2.0.0, the issue should be fixed.
Reopen if needed.
Thank you!
