### ISSUE TITLE
Keyboard Bug

### ISSUE THREAD

**Issue by sandbox-apps** [Tkko/Flutter_Pinput#56]
Steps to Reproduce
1. Tap the PinPut field to open or show the keyboard.
2. Tap again the PinPut field while the keyboard is open.

Problem:
The Keyboard is closing then showing again.

Actual:
If the keyboard is already shown tapping the Pinput field again would not cause the keyboard to hide and show again. It should be expected to do nothing unless the keyboard is hidden at first

**Comment by Tkko** [comment]
Sorry for late response,
Just uploaded new refactored version 2.0.0, the issue should be fixed.
Reopen if needed.
Thank you!
