### ISSUE TITLE
getting unexpected borders behind pinput

### ISSUE THREAD

**Issue by Aryan-Solanki** [Tkko/Flutter_PinPut#58]
![image](https://user-images.githubusercontent.com/37494973/128916343-217f3684-9adb-48ff-89a2-7d57706124cd.png)

final BoxDecoration pinPutDecoration = BoxDecoration(
      color: kPrimaryColor,
      borderRadius: BorderRadius.circular(5.0),
    );

boxedPinPutWithPreFilledSymbol() {
      return PinPut(
        withCursor: true,
        fieldsCount: 6,
        textStyle: const TextStyle(fontSize: 25.0, color: Colors.white),
        eachFieldWidth: getProportionateScreenWidth(50),
        eachFieldHeight: getProportionateScreenHeight(50),
        onSubmit: (String pin) async {
          try {
            await auth
                .signInWithCredential(PhoneAuthProvider.credential(
                    verificationId: _verificationCode, smsCode: pin))
                .then((value) async {
              if (value.user != null) {
                phone_uid = auth.currentUser.uid;
                auth.signOut();
                String password = await _userServices.getKeyPass(phone_uid);
                print("password is $password");
                await _auth.signIn(
                    email: number + "@orev.user", password: password);
                var uid_real = _auth.user.uid;
                print("Email UID is $uid_real");
                Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                        builder: (context) =>
                            UpdatePasswordScreen(phone_uid: phone_uid)));
              }
            });
          } catch (e) {
            print(e);
          }
        },
        focusNode: _pinPutFocusNode,
        controller: _pinPutController,
        submittedFieldDecoration: pinPutDecoration,
        selectedFieldDecoration:
        pinPutDecoration.copyWith(color: Colors.lightGreen),
        followingFieldDecoration: pinPutDecoration,
      );
    }

**Comment by tibfox** [comment]
ca you please provide a solution @Aryan-Solanki ?

**Comment by Aryan-Solanki** [comment]
@tibfox actually this pinput is made on top of textfield..and i have borders property in theme of my project.. just do this

Theme(
        data: Theme.of(context).copyWith(
            inputDecorationTheme: InputDecorationTheme(
              floatingLabelBehavior: FloatingLabelBehavior.always,
              contentPadding: EdgeInsets.symmetric(horizontal: 42, vertical: 20),
            )
        ),
       child: PinPut(
               //pinput code
        ),
)

**Comment by Aryan-Solanki** [comment]
you can remove label property if you want :)
