### ISSUE TITLE
Hint text not show

### ISSUE THREAD

**Issue by skripsimu** [Tkko/Flutter_Pinput#59]
I've added hint text but it's not showing when run, even though I've changed the hint style

<img width="477" alt="Screen Shot 2021-08-23 at 11 40 34" src="https://user-images.githubusercontent.com/35763779/130390898-4f13e243-bf72-43a1-9a48-4aed406f3df2.png">
<img width="477" alt="Screen Shot 2021-08-23 at 11 41 11" src="https://user-images.githubusercontent.com/35763779/130390934-c9f5e71d-f13d-4613-8dc4-5bb8fc26a903.png">

**Comment by skripsimu** [comment]
I found the hinttext is behind the textfield, and only in the first box
<img width="845" alt="Screen Shot 2021-08-23 at 11 49 20" src="https://user-images.githubusercontent.com/35763779/130391507-40900a2a-e5b8-4c16-80fa-edeb6e90f9b2.png">

**Comment by Tkko** [comment]
Sorry for late response, I guess you already find the solution.
Just uploaded new refactored version 2.0.0, you can use preFilledWidget.
