### ISSUE TITLE
Submit without clearing inputs

### ISSUE THREAD

**Issue by hukjordanjanaq** [Tkko/Flutter_Pinput#61]
Hi, i'm submiting the input after it's fill, and hiding keyboard, but it disapear the inputs value.

https://user-images.githubusercontent.com/48919342/131780883-7f05b1bf-fc1c-479d-8e66-b3ab05b5acce.mov

Nice library, Thank you so much.

**Comment by jordanjanaq** [comment]
Now  I could test, I'm adding an action keyboard "done" for verify and it clears everything. I want to know if this is the default behavior.


Uploading Grabación de pantalla 2021-11-24 a la(s) 17.15.15.mov…

<img width="417" alt="Captura de Pantalla 2021-11-24 a la(s) 17 13 08" src="https://user-images.githubusercontent.com/48919342/143319307-83d645e6-ef70-4582-954a-84a3de9dd85b.png">

<img width="352" alt="Captura de Pantalla 2021-11-24 a la(s) 17 13 30" src="https://user-images.githubusercontent.com/48919342/143319349-446380d5-e1e0-4c26-914a-1742441615f9.png">

**Comment by jordanjanaq** [comment]
Now  I could test, I'm adding an action keyboard "done" for verify and it clears everything. I want to know if this is the default behavior.

<img width="417" alt="Captura de Pantalla 2021-11-24 a la(s) 17 13 08" src="https://user-images.githubusercontent.com/48919342/143319307-83d645e6-ef70-4582-954a-84a3de9dd85b.png">

<img width="352" alt="Captura de Pantalla 2021-11-24 a la(s) 17 13 30" src="https://user-images.githubusercontent.com/48919342/143319349-446380d5-e1e0-4c26-914a-1742441615f9.png">

**Comment by jordanjanaq** [comment]
https://user-images.githubusercontent.com/48919342/143319715-8785faa9-ebcb-4b79-bff5-f12edb5152bd.mov

**Comment by Tkko** [comment]
Sorry for late response,
Just uploaded new refactored version 2.0.0, the issue should be fixed.
Reopen if needed.
Thank you!
