### ISSUE TITLE
inverts input on web

### ISSUE THREAD

**Issue by ipainchaud** [Tkko/Flutter_PinPut#66]
![image](https://user-images.githubusercontent.com/5298744/137600190-a7a0f953-5030-49cd-b6fd-a49b0a1badd6.png)
I entered 1, then 2 then 3.... This was reproduced on many environments... As you enter the numbers, it is possible to see the controls "flash" and I'm pretty sure what I've seen is the fields being redrawn in the wrong order. I'm going to have a quick look at your code to see if I can figure it out. This was working not long ago and is not an issue on android.

used version:
>$ flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (26 hours ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

and used dependencies:
>dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.0.2
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  intl_phone_field: ^2.1.0
  pinput: ^1.2.1
  toml: ^0.12.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  uuid: ^3.0.4
  device_info_plus: ^3.0.1

**Comment by ipainchaud** [comment]
The issue is linked with semantics. If you want to make your web application easy to interact with when used with Screen Readers, you want semantics to be enabled by default. That was the culprit.
` RendererBinding.instance?.setSemanticsEnabled(true);`
We are communicating this with the Flutter team.

**Comment by vsomayaji** [comment]
@Tkko I added some details to https://github.com/flutter/flutter/issues/92606#issuecomment-960412259. There appears to be an issue with accessibility and the [`enableInteractiveSelection`](https://api.flutter.dev/flutter/material/TextField/enableInteractiveSelection.html) property. If `enableInteractiveSelection` is `true` the issue goes away, but that may have other side effects.

**Comment by Tkko** [comment]
@vsomayaji I'm uploading a new version with the `enableInteractiveSelection` property, it is also essential for the paste option.

**Comment by vsomayaji** [comment]
@Tkko you're the best! Thank you for the quick turnaround. I've verified that we no longer see this issue with version `1.2.2`.
