### ISSUE TITLE
Error: No named parameter with the name 'floatingLabelStyle'.

### ISSUE THREAD

**Issue by mshamsi502** [Tkko/Flutter_Pinput#67]
I get this error message from pinput-v1.2.2 :

```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-1.2.2/lib/pin_put/pin_put_state.dart:35:7: Error: No named parameter with the name 'floatingLabelStyle'.
      floatingLabelStyle: hiddenTextStyle,
      ^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/input_decorator.dart:2517:9: Context: Found this candidate, but the arguments don't match.
  const InputDecoration({
        ^^^^^^^^^^^^^^^
3

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by mohmmedkhalifa** [comment]
same here

**Comment by mshamsi502** [comment]
@mohmmedkhalifa 
I opened this file : 
`C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-1.2.2/lib/pin_put/pin_put_state.dart`
and delete this line :
` floatingLabelStyle: hiddenTextStyle,`
its work for me

**Comment by mohmmedkhalifa** [comment]
> @mohmmedkhalifa I opened this file : `C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/pinput-1.2.2/lib/pin_put/pin_put_state.dart` and delete this line : ` floatingLabelStyle: hiddenTextStyle,` its work for me

thanks, its worked with me

**Comment by H4NSWORST** [comment]
Your flutter version is probably too low. I'm experiencing the same problem on flutter version 2.0.6. The floatingLabelStyle property of the InputDecoration class was added around june 2021. For anyone with this problem upgrading your flutter version to 2.2.3 or higher may help instead of the above solution.

**Comment by Tkko** [comment]
Sorry for late response,
Just uploaded new refactored version 2.0.0, native TextField customization is not supported anymore.
Thank you!
