### ISSUE TITLE
deprecated hideCurrentSnackBar showSnackBar

### ISSUE THREAD

**Issue by CogarCarlosCeballos** [Tkko/Flutter_Pinput#69]
Scaffold.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(snackBar);

Can be changed to:

ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(snackBar);

**Comment by Tkko** [comment]
Yep, Thanks.

**Comment by Tkko** [comment]
Fixed, Just uploaded new refactored version 2.0.0. Thank you!
