### ISSUE TITLE
backspace on the keyboard does not work 

### ISSUE THREAD

**Issue by pouledodue** [Tkko/Flutter_PinPut#7]
backspace on the keyboard does not work

**Comment by Tkko** [comment]
Thanks for feedback, right now there is workaround to use action button

**Comment by dhavalagile** [comment]
I am facing the same issues unable to detect backspace in a flutter.
refer [#14809](https://github.com/flutter/flutter/issues/14809)

**Comment by Tkko** [comment]
Solved In 0.1.10+ version.
