### ISSUE TITLE
How to change the space between boxes?

### ISSUE THREAD

**Issue by SametSahin10** [Tkko/Flutter_Pinput#70]
Is it possible to change the horizontal space between individual fields? I've tried to set `eachFieldMargin` to `EdgetInsets.zero` but I got the error below:

`type 'Null' is not a subtype of type 'EdgeInsetsGeometry' in type cast`

**Comment by byshy** [comment]
To remove the space between the fields use `mainAxisSize: MainAxisSize.min,`, you can't set a different space between fields,  but combining `mainAxisSize` with `eachFieldMargin` gave me the design I was looking for.

<img width="198" alt="Screen Shot 2022-01-02 at 12 39 32 PM" src="https://user-images.githubusercontent.com/33957976/147873225-0eb6adc0-c9e6-4d8a-b9aa-f23d3a0e1422.png">

**Comment by Tkko** [comment]
Fixed, Just uploaded new refactored version 2.0.0. Thank you!
