### ISSUE TITLE
validator and autovalidateMode removed from package?

### ISSUE THREAD

**Issue by naamapps** [Tkko/Flutter_Pinput#75]
Hey,
I just upgraded to latest version, and trying migrate from 1.2.0.
And I see that validator and autovalidateMode are removed.

Can you add them again?
It very useful to show a custom error message below the pinput.

Thanks

**Comment by Tkko** [comment]
Could you share the screenshot of how error message was displayed?

**Comment by naamapps** [comment]
It looks just like a normal flutter textfield error that pops below the text field when there is a validation error.
I used the validator to return a custom error message (your pin is incorrect) or null when the user is typing and there are no reason to show an error.

**Comment by Tkko** [comment]
The TextField's decoration had conflicts with the widget (in some cases), you can pass 'showError' parameter to activate error state decoration, but error text is not included in current version, for now you can easily put Text('Erorr') under the Pinput. I'll think about adding Adding errorText again.

**Comment by naamapps** [comment]
Yeah so for now I put the error below the pinput.. but this is not ideal because I think it should come out of the box - like a regular textfield.
Thanks

**Comment by Tkko** [comment]
Yeah, now that I think about it you are right.

**Comment by Tkko** [comment]
Hi @naamapps, in 99% cases pin validation will be done after pin completion, and validation while typing will not be important, right?

I propose, Adding errorText, errorTextStyle, errorBuilder (for custom error widget), and validation after user submits the pin, clearing error after user interaction + showing and hiding errorText with animation, WDYT? 
Does this solution works for you?

I don't want to bloat Widget with unimportant functionalities.

**Comment by naamapps** [comment]
Hey @Tkko,
Yes that sounds good.
I think that the look and feel should be like the flutter textfield error (red text and with animation).

**Comment by Tkko** [comment]
Done, Version 2.1.0.
Reopen if needed.
