### ISSUE TITLE
my old app is broken after upgrading to latest version

### ISSUE THREAD

**Issue by mohadel92** [Tkko/Flutter_Pinput#76]
Hi,
please at least provide a documentation for upgrading to latest version 
all `fieldsCount.eachFieldHeight,onSubmit,submittedFieldDecoration,selectedFieldDecoration,followingFieldDecoration`

are missing from the new package

**Comment by Tkko** [comment]
@mohadel92 Please see the [Changelog](https://github.com/Tkko/Flutter_Pinput/blob/master/CHANGELOG.md) and let me know if it is helpful?

**Comment by mohadel92** [comment]
thanks  i didn't found it in the first place , at mean time i moved back to an older version
