### ISSUE TITLE
Add an onLongPress property

### ISSUE THREAD

**Issue by naamapps** [Tkko/Flutter_Pinput#77]
Hey,
Previous version I wrapped the pinput in a gesture detector to detect a long press and show a custom dialog to paste text from clipboard.

However, in latest version it simply doesn't work - if I long press, the textfield toolbar appears, and this is not my intentions (bad UX).

So to fix this, you can add an onLongPress property, if it's null - the long press will cascade to the input itself and show the toolbar.
If it is not null - the callback will fire.

Thanks :)

**Comment by Tkko** [comment]
Yeah good point, will do something about it soon.

**Comment by Tkko** [comment]
Checkout the version 2.0.4.
- Added `onLongPress`

note that to catch `onLongPress` event `enableInteractiveSelection` should be false

**Comment by Tkko** [comment]
@naamapps  Checkout the version 2.0.4.

Added onLongPress
note that to catch onLongPress event enableInteractiveSelection should be false.

**Comment by naamapps** [comment]
Thanks @Tkko,
Works flawlessly.
