### ISSUE TITLE
Not able to clear the pin input

### ISSUE THREAD

**Issue by jh-tan** [Tkko/Flutter_Pinput#78]
Hi, I just upgraded to latest version and when i tried to clear the pin input through ` _pinPutController.text = "";`
and `_pinPutController.clear();`, it is not working as expected. The pin is not removed.

Please suggest that how can I clear the pin input. Thank you.

**Comment by Tkko** [comment]
Hi, I'm checking and `_pinPutController.clear();` works fine, could you share the code snippet?

**Comment by jh-tan** [comment]
`
class PinInput extends StatelessWidget {
  final String verificationCode;
  final String phoneNumber;
  PinInput({Key? key, required this.verificationCode, required this.phoneNumber}) : super(key: key);

  final TextEditingController _pinPutController = TextEditingController();
  final FocusNode _pinPutFocusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      margin: const EdgeInsets.all(20.0),
      padding: const EdgeInsets.all(20.0),
      child: Pinput(
          length: 6,
          onCompleted: (String pin) async {
            User? user = await FirebaseAuthentication()
                .loginWithPhone(verificationCode: verificationCode, pin: pin);
            if (user == null) {
              FocusScope.of(context).unfocus();
              _pinPutController.text = "";
              GlobalSnackBar().show(context, "Invalid Pin Number");
            } else if (await FirebaseDatabase().isExist(user.uid)) {
              Navigator.pushReplacementNamed(context, 'Home');
            } else {
              Navigator.pushReplacementNamed(context, Register.routeName,
                  arguments: UserArguments(phoneNumber, user.uid));
            }
          },
          focusNode: _pinPutFocusNode,
          controller: _pinPutController,
          defaultPinTheme: defaultPinTheme,
          focusedPinTheme: focusedPinTheme,
          submittedPinTheme: submittedPinTheme),
    );
  }

  static final defaultPinTheme = PinTheme(
    width: 56,
    height: 56,
    textStyle: const TextStyle(
        fontSize: 20, color: Color.fromRGBO(30, 60, 87, 1), fontWeight: FontWeight.w600),
    decoration: BoxDecoration(
      border: Border.all(color: const Color.fromARGB(255, 104, 176, 235)),
      borderRadius: BorderRadius.circular(20),
    ),
  );

  final focusedPinTheme = defaultPinTheme.copyDecorationWith(
    border: Border.all(color: const Color.fromRGBO(114, 178, 238, 1)),
    borderRadius: BorderRadius.circular(8),
  );

  final submittedPinTheme = defaultPinTheme.copyWith(
    decoration: defaultPinTheme.decoration?.copyWith(
      color: const Color.fromRGBO(234, 239, 243, 1),
    ),
  );
}`

**Comment by jh-tan** [comment]
code: 
```
class PinInput extends StatelessWidget {
  final String verificationCode;
  final String phoneNumber;
  PinInput({Key? key, required this.verificationCode, required this.phoneNumber}) : super(key: key);

  final TextEditingController _pinPutController = TextEditingController();
  final FocusNode _pinPutFocusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      margin: const EdgeInsets.all(20.0),
      padding: const EdgeInsets.all(20.0),
      child: Pinput(
          length: 6,
          onCompleted: (String pin) async {
            User? user = await FirebaseAuthentication()
                .loginWithPhone(verificationCode: verificationCode, pin: pin);
            if (user == null) {
              FocusScope.of(context).unfocus();
              _pinPutController.text = "";
              GlobalSnackBar().show(context, "Invalid Pin Number");
            } else if (await FirebaseDatabase().isExist(user.uid)) {
              Navigator.pushReplacementNamed(context, 'Home');
            } else {
              Navigator.pushReplacementNamed(context, Register.routeName,
                  arguments: UserArguments(phoneNumber, user.uid));
            }
          },
          focusNode: _pinPutFocusNode,
          controller: _pinPutController,
          defaultPinTheme: defaultPinTheme,
          focusedPinTheme: focusedPinTheme,
          submittedPinTheme: submittedPinTheme),
    );
  }

  static final defaultPinTheme = PinTheme(
    width: 56,
    height: 56,
    textStyle: const TextStyle(
        fontSize: 20, color: Color.fromRGBO(30, 60, 87, 1), fontWeight: FontWeight.w600),
    decoration: BoxDecoration(
      border: Border.all(color: const Color.fromARGB(255, 104, 176, 235)),
      borderRadius: BorderRadius.circular(20),
    ),
  );

  final focusedPinTheme = defaultPinTheme.copyDecorationWith(
    border: Border.all(color: const Color.fromRGBO(114, 178, 238, 1)),
    borderRadius: BorderRadius.circular(8),
  );

  final submittedPinTheme = defaultPinTheme.copyWith(
    decoration: defaultPinTheme.decoration?.copyWith(
      color: const Color.fromRGBO(234, 239, 243, 1),
    ),
  );
}
```

**Comment by Tkko** [comment]
I'll take care ASAP.

**Comment by Tkko** [comment]
Found the problem, I will upload new version today

**Comment by jh-tan** [comment]
@Tkko Yes, it worked with stateful widget. I will go with it first as a temporary solution until the new patch come up. Thanks for the help.

**Comment by cedvdb** [comment]
hasn't that break autofocus ?

**Comment by Tkko** [comment]
@jh-tan  BTW, You need stateful widget anyway, you should dispose `_pinPutController` and `_pinPutFocusNode`

```
  @override
  void dispose() {
    _pinPutController.dispose();
    _pinPutFocusNode.dispose();
    super.dispose();
  }
```

**Comment by Tkko** [comment]
Done, Version 2.1.0.
