### ISSUE TITLE
Built in sms autofill for Android

### ISSUE THREAD

**Issue by Tkko** [Tkko/Flutter_Pinput#79]
Integrate SMS verification [APIs](https://developers.google.com/identity/sms-retriever/overview) for Android.

**Comment by Tkko** [comment]
Done in version 2.2.0

**Comment by setu-dev** [comment]
How to use `smsRetrieverApi`?

     androidSmsAutofillMethod: AndroidSmsAutofillMethod.smsRetrieverApi,

just adding this doesn't work .. 
but `smsUserConsentApi` works this way.

**Comment by Tkko** [comment]
@setu-dev Take a look at the docs https://github.com/Tkko/Flutter_Pinput#sms-retriever-api

**Comment by ousvat** [comment]
@Tkko What does `To use Retriever API you need The App [signature](https://stackoverflow.com/questions/53849023/android-sms-retriever-api-computing-apps-hash-string-problem)` mean? What should I do in order to work?
