### ISSUE TITLE
OnClipboardFound not working

### ISSUE THREAD

**Issue by LisaLamparter** [Tkko/Flutter_Pinput#80]
Hi there,

Thanks for providing such a nice library.
I tried to implement clipboard functionality. Unfortunately the method "onClipboardFound" never gets called.

I already debugged into the code, the lifecycle method "didChangeAppLifecycleState" in pinput_state is never called.
I think, initState() should be extended to contain `    WidgetsBinding.instance?.addObserver(this);` and dispose() should be extended to contain `WidgetsBinding.instance?.removeObserver(this);`.

Can you fix this or did I miss something ? In this case, a working example would be nice.

Thanks in advance,
Lisa

**Comment by Tkko** [comment]
@LisaLamparter thanks for rising the issue.
You are right, I'll upload the fix soon.

**Comment by Tkko** [comment]
@LisaLamparter Checkout version 2.2.4

**Comment by LisaLamparter** [comment]
Wow, that was fast ;-) Thanks a lot! Now it works ... 👍
