### ISSUE TITLE
Sms autofill works only when you get the first sms

### ISSUE THREAD

**Issue by wantroba** [Tkko/Flutter_Pinput#81]
If the app receives a second sms the autofill doesn't work

**Comment by Tkko** [comment]
Do you really need to listen for second SMS?

**Comment by Tkko** [comment]
Makes sense, will do something about it.

**Comment by wantroba** [comment]
Tks. It's not a big problem. The actual version is really good and functional!

**Comment by Tkko** [comment]
## 2.2.7 -04/04/2022
- Option to listen for multiple sms on android
| Property   | Meaning/Default |
|------------|:-------:|
| listenForMultipleSmsOnAndroid  | false |
