### ISSUE TITLE
Can't center PIN input along with error message 

### ISSUE THREAD

**Issue by akrupych** [Tkko/Flutter_Pinput#83]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/1413677/160297768-a5788cf5-c2f6-44ab-94ad-6d83d6dfb983.png">
Can't find a way to center PIN input if error message takes more space than input.

**Comment by Tkko** [comment]
Try to use errorBuilder and limit the width of it, also, could you share the desired design of the pin input when error is shown?

**Comment by akrupych** [comment]
If possible, I'd like it look like this:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/1413677/160335735-10d11374-77b4-4635-bc20-390fd970bcd1.png">

**Comment by Tkko** [comment]
@akrupych this should help
## 2.2.5 -28/03/2022
Added

| Property   | Meaning/Default |
|------------|:-------:|
| crossAxisAlignment  | CrossAxisAlignment.start |

**Comment by akrupych** [comment]
@Tkko works great, thanks!

One last thing though :) Any chance I can align multi-line error?
<img width="216" alt="image" src="https://user-images.githubusercontent.com/1413677/160394205-c535837e-9c6d-4855-9405-ab6bd085d02d.png">

**Comment by Tkko** [comment]
Did you try `errorBuilder`?

**Comment by akrupych** [comment]
Thanks, the builder was what I needed. Sorry for trouble.
