### ISSUE TITLE
SMS autofill does not work on android

### ISSUE THREAD

**Issue by ousvat** [Tkko/Flutter_Pinput#84]
I tried to use both ` androidSmsAutofillMethod.smsRetrieverApi` and `AndroidSmsAutofillMethod.smsUserConsentApi` but none of them autocomplete the field when I am receiving a sms.

Here is all my code:
```
Pinput(
      controller: _textEditingController,
      length: widget.digitCount,
      keyboardType: widget.keyboardType,
      textCapitalization: widget.textCapitalization ?? TextCapitalization.none,
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      androidSmsAutofillMethod: AndroidSmsAutofillMethod.smsRetrieverApi,
      separator: SizedBox(width: 2),
      defaultPinTheme: _defaultPinTheme(),
      showCursor: false,
      focusedPinTheme: _defaultPinTheme().copyDecorationWith(
        border: Border.all(
          color: widget.hasSucceeded
              ? _succeedColor
              : Theme.of(context).colorScheme.primary,
          width: 2,
        ),
      ),
      errorPinTheme: _defaultPinTheme().copyDecorationWith(
        border: Border.all(
          color: Theme.of(context).colorScheme.error,
          width: 2,
        ),
      ),
      onCompleted: (code) {
        widget.onValidate(code);
      },
      onTap: () {
        if (widget.hasError) {
          _textEditingController.clear();
        }
        widget.onFocus();
      },
    );
  }
```

**Comment by Tkko** [comment]
@ousvat share the SMS content please.

**Comment by ousvat** [comment]
> @ousvat share the SMS content please.

A sms looks like `Activation code 1234` .

**Comment by Tkko** [comment]
@ousvat  When use use 
`androidSmsAutofillMethod: AndroidSmsAutofillMethod.smsUserConsentApi` can't your see the dialog like this?
![Screenshot_20220330_173202](https://user-images.githubusercontent.com/26390946/160846592-807534dd-de19-410f-9877-fee959a3b97c.png)
Post more details
- Android version
- Flutter version
- Device

**Comment by ousvat** [comment]
No.. I can't see anything.

Android version: 10
Flutter version: 2.10.3
Device: Samsung Note 9

**Comment by ousvat** [comment]
There is nothing displayed in console..

**Comment by ousvat** [comment]
> There is nothing displayed in console..
> 
> Do you think it would be related to the app signature?

So yeah.. the issue is on the message type.. It should look like:
```
Activation code 1234
ufTCFrxN/y1
```

**Comment by Tkko** [comment]
`smsUserConsentApi` should work without the App signature, but since I can't reproduce the issue let's suppose the issue as closed, if this problem still remaining for anyone please let me know.

**Comment by Keval-patel1** [comment]
disconnecting from surface 0xb4000075004d3300, reason disconnectFromSurface
[MediaCodec.release](id:2190000001b,api:3,p:537,c:537) disconnect: api 3

I am facing this issue
