### ISSUE TITLE
'NoSuchMethodError' occurs when clipboardData is null

### ISSUE THREAD

**Issue by mwgriffiths88** [Tkko/Flutter_PinPut#9]
A `NoSuchMethodError` exception occurs when trying to access the `text` property of `clipboardData` when it's null. The relevant code is:

https://github.com/Tkko/Flutter_PinPut/blob/5fb62e572bc356e8fcd35236617acffa9dc61316/lib/pin_put/pin_put_bloc.dart#L51-L56

**Comment by mwgriffiths88** [comment]
https://github.com/Tkko/Flutter_PinPut/pull/10

**Comment by Tkko** [comment]
Merged your request, thanks.
