### ISSUE TITLE
Is it possible to fill the box from right to left?

### ISSUE THREAD

**Issue by robertoltrocha** [Tkko/Flutter_Pinput#90]
Hi
It is a great package.
I have a request, but I need to fill box from  right to left. Is it possible to do that?

thanks

**Comment by Tkko** [comment]
Hi @robertoltrocha, do you mean to set `textDirection` property to `rtl`, right? not possible yet.

**Comment by robertoltrocha** [comment]
Hi,

not inside the box.

focus first right box and go left box, go left box, go left box when tap a number.

sds

**Comment by Tkko** [comment]
@robertoltrocha this should work

```
    return Directionality(
      textDirection: TextDirection.rtl,
      child: Pinput(),
    );

```

**Comment by Tkko** [comment]
Closing the issue, feel free to reopen if provided solution doesn't work.
