### ISSUE TITLE
scrollPadding

### ISSUE THREAD

**Issue by lironzemingo** [Tkko/Flutter_Pinput#91]
I didn't find a way to add scrollPadding, like in regular TextField. did I miss something?

**Comment by lironzemingo** [comment]
I have a button under my PinPut field, and when the keyboard is displayed, I want it to be below the button, as well as the field. will try what you suggest

**Comment by Tkko** [comment]
> I have a button under my PinPut field, and when the keyboard is displayed, I want it to be below the button, as well as the field. will try what you suggest

My suggestion won't work, I thought you were trying something else, you need to implement that case on your side I think.

**Comment by Tkko** [comment]
Hi @lironzemingo, just uploaded the new version with `scrollPadding`, thank you for opening the issue.

## 2.2.10 -31/05/2022
- When this widget receives focus and is not completely visible (for example scrolled partially
  off the screen or overlapped by the keyboard)
  then it will attempt to make itself visible by scrolling a surrounding [Scrollable], if one is present.
  This value controls how far from the edges of a [Scrollable] the TextField will be positioned after the scroll.
  | Property   | Meaning/Default |
  |------------|:-------:|
  | scrollPadding  | EdgeInsets.all(20) |

**Comment by lironzemingo** [comment]
Amazing! thanks!
