### ISSUE TITLE
How to edit particular digit and change it to new value without deleting other digits?

### ISSUE THREAD

**Issue by Aashutosh3804** [Tkko/Flutter_Pinput#92]
I want user to be able to edit any value in-between that is they should be able to click on particular field and edit it rather than deleting all the previous values to edit that place
How I can achieve this ?

**Comment by Tkko** [comment]
Hi, good idea, but that's not possible with current implementation.

**Comment by Aashutosh3804** [comment]
> Hi, good idea, but that's not possible with current implementation.

Any workaround you can suggest, to change in library to accomplish it? it will be really helpful just any hint

**Comment by Tkko** [comment]
selected index should return the position of the cursor
https://github.com/Tkko/Flutter_Pinput/blob/48e7a7a4193e872c4a66a5dca6651f8c254b0f13/lib/src/pinput_state.dart#L68
`  int get selectedIndex => _effectiveController.selection.baseOffset;
`

And when you tap on individual boxes you have to change the cursor position respectively

`_effectiveController.selection = TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));`

**Comment by Aashutosh3804** [comment]
> TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));

Thank you very much for such prompt reply 
just one last thing tappedPinIndex how would I get that as in _semanticsOnTap I did get any index

`_effectiveController.selection = TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));`

this line should changed in _semanticsOnTap right ? just tell me how to get the tapped index

**Comment by Tkko** [comment]
> > TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));
> 
> Thank you very much for such prompt reply just one last thing tappedPinIndex how would I get that as in _semanticsOnTap I did'nt get any index
> 
> `_effectiveController.selection = TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));`
> 
> this line should changed in _semanticsOnTap right ? just tell me how to get the tapped index

Nope, you should add onTap callback in _PinItem with GestureDetector
https://github.com/Tkko/Flutter_Pinput/blob/48e7a7a4193e872c4a66a5dca6651f8c254b0f13/lib/src/pinput_state.dart#L456

**Comment by Aashutosh3804** [comment]
> > > TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));
> > 
> > 
> > Thank you very much for such prompt reply just one last thing tappedPinIndex how would I get that as in _semanticsOnTap I did'nt get any index
> > `_effectiveController.selection = TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));`
> > this line should changed in _semanticsOnTap right ? just tell me how to get the tapped index
> 
> Nope, you should add onTap callback in _PinItem with GestureDetector
> 
> https://github.com/Tkko/Flutter_Pinput/blob/48e7a7a4193e872c4a66a5dca6651f8c254b0f13/lib/src/pinput_state.dart#L456

`GestureDetector(
      onTap: () {
        state._effectiveController.selection =
            TextSelection.fromPosition(TextPosition(offset: index));
      },
      child: Flexible(
        child: AnimatedContainer(
          height: pinTheme.height,
          width: pinTheme.width,
          constraints: pinTheme.constraints,
          padding: pinTheme.padding,
          margin: pinTheme.margin,
          decoration: pinTheme.decoration,
          alignment: state.widget.pinContentAlignment,
          duration: state.widget.animationDuration,
          curve: state.widget.animationCurve,
          child: AnimatedSwitcher(
            switchInCurve: state.widget.animationCurve,
            switchOutCurve: state.widget.animationCurve,
            duration: state.widget.animationDuration,
            transitionBuilder: (child, animation) {
              return _getTransition(child, animation);
            },
            child: _buildFieldContent(index, pinTheme),
          ),
        ),
      ),
    );`

Its showing Incorrect use of ParentDataWidget error

**Comment by Tkko** [comment]
> > > > TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));
> > > 
> > > 
> > > Thank you very much for such prompt reply just one last thing tappedPinIndex how would I get that as in _semanticsOnTap I did'nt get any index
> > > `_effectiveController.selection = TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));`
> > > this line should changed in _semanticsOnTap right ? just tell me how to get the tapped index
> > 
> > 
> > Nope, you should add onTap callback in _PinItem with GestureDetector
> > https://github.com/Tkko/Flutter_Pinput/blob/48e7a7a4193e872c4a66a5dca6651f8c254b0f13/lib/src/pinput_state.dart#L456
> 
> Its not working. Firstly I want to be able to select any field and change its value. So when its empty it showing error as there no text yet written. Is there a way to do that

What I wrote was not the whole solution, just the way I imagined implementing it, I will to add the feature ASAP, but can't tell you the deadline RN.

**Comment by Aashutosh3804** [comment]
> > > > > TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));
> > > > 
> > > > 
> > > > Thank you very much for such prompt reply just one last thing tappedPinIndex how would I get that as in _semanticsOnTap I did'nt get any index
> > > > `_effectiveController.selection = TextSelection.fromPosition(TextPosition(offset: tappedPinIndex));`
> > > > this line should changed in _semanticsOnTap right ? just tell me how to get the tapped index
> > > 
> > > 
> > > Nope, you should add onTap callback in _PinItem with GestureDetector
> > > https://github.com/Tkko/Flutter_Pinput/blob/48e7a7a4193e872c4a66a5dca6651f8c254b0f13/lib/src/pinput_state.dart#L456
> > 
> > 
> > Its not working. Firstly I want to be able to select any field and change its value. So when its empty it showing error as there no text yet written. Is there a way to do that
> 
> What I wrote was not the whole solution, just the way I imagined implementing it, I will to add the feature ASAP, but can't tell you the deadline RN.
> 
> Update: Just tried it a bit and I can say it will introduce new problems to solve, so it's not an easy feature to add

Oh ok , thanks for trying will think of different way

**Comment by nicks258** [comment]
Any update on this feature? @Tkko ?

**Comment by Tkko** [comment]
@nicks258 Nothing so far, my weekends are pretty busy these days 🫢, If anyone is available to implement this feature I'd be happy review and merge the PR

**Comment by Ssiswent** [comment]
How about now? Thanks.
