### ISSUE TITLE
Flutter constraints too loose

### ISSUE THREAD

**Issue by t-animal** [Tkko/Flutter_Pinput#96]
This project doesn't compile with flutter 2.5.1, but the pubspec.yaml allows installing it for versions `flutter: ">=1.17.0"`

At least [this](https://github.com/flutter/flutter/commit/33755f203dfeae491f586a73abdf4e400749f32a#diff-701a97b414026a5c87a06b546bb38ca70be2aa0ce44cbf170f4b43e8defcc91aR612) `copyWith` is missing. Judging from the tag list in the header on github I'd guess that the earliest released version that included this line is 2.8.0, but I'm not entirely sure how to interpret this list.

**Comment by Tkko** [comment]
Hi @t-animal, let me check

**Comment by Tkko** [comment]
Bumped the Flutter SDK version in version [2.2.13](https://github.com/Tkko/Flutter_Pinput/releases/tag/v2.2.13)
