### ISSUE TITLE
SMSConsentAPI Mode localization

### ISSUE THREAD

**Issue by ronaldgosso** [Tkko/Flutter_Pinput#99]
How can I localize (l10n) or change the SMS ConsentAPI Mode message?
From: **Allow {appName} to read the message below and enter the code ?**
To: **{appName} が以下のメッセージを読み、コードを入力できるようにしますか?**

**Comment by Tkko** [comment]
Hi @ronaldgosso, I'm not sure yet, I'll try to find the solution.

**Comment by Tkko** [comment]
@ronaldgosso  Seems like the only option to localize the prompt text is to change the device locale from settings.
